-- queries/p2_grain_and_identity.sql — P2 · grain-and-identity, every query with the
-- answer it returned. Written by scratchpad/ingest/p2_grain.py; re-runnable verbatim.
-- measured_at 2026-09-18T08:22:44+02:00 · DuckDB read-only via connection.yaml · engine reports no
-- scanned bytes, so none is claimed.
--
-- The greedy route (orderrows, sales, currencyexchange) is mac_admit_identity.py/1's own
-- SQL, reproduced by that tool and recorded in RUN.md rather than duplicated here.

-- ── ADMIT/orders ──────────────────────────────────────────────────────────────────────────
SELECT 'ALL' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "CustomerKey") AS dv
      FROM main.orders GROUP BY "OrderKey")
UNION ALL
SELECT 'OrderKey' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "CustomerKey") AS dv
      FROM main.orders)
ORDER BY 1;
--   →
--   - disagree: 0
--     groups: 93470
--     omitted: ALL
--     split: 0
--   - disagree: 1
--     groups: 1
--     omitted: OrderKey
--     split: 1

-- ── DEPEND/orders ─────────────────────────────────────────────────────────────────────────
# generated by mac_admit_identity.dependence_sql(
#     relation='main.orders',
#     determinants=['CustomerKey', 'StoreKey', 'DT', 'DeliveryDate', 'CurrencyCode'],
#     dependents=['CustomerKey', 'StoreKey', 'DT', 'DeliveryDate', 'CurrencyCode'],
#     stratum=None)
# 5 grouped branch(es) UNION ALL'd; a branch reports max(count(DISTINCT b)) per
# dependent b, and b is determined by a when that max is 1.
--   →
--   determinants: 5
--   dependents: 5
--   dependences_found: 1
--   CurrencyCode:
--   - CustomerKey

-- ── ADMIT/customer ────────────────────────────────────────────────────────────────────────
SELECT 'ALL' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "GeoAreaKey") AS dv
      FROM main.customer GROUP BY "CustomerKey")
UNION ALL
SELECT 'CustomerKey' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "GeoAreaKey") AS dv
      FROM main.customer)
ORDER BY 1;
--   →
--   - disagree: 0
--     groups: 104990
--     omitted: ALL
--     split: 0
--   - disagree: 1
--     groups: 1
--     omitted: CustomerKey
--     split: 1

-- ── DEPEND/customer ───────────────────────────────────────────────────────────────────────
# generated by mac_admit_identity.dependence_sql(
#     relation='main.customer',
#     determinants=['GeoAreaKey', 'StartDT', 'EndDT', 'Continent', 'Gender', 'Title', 'GivenName', 'MiddleInitial', 'Surname', 'StreetAddress', 'City', 'State', 'StateFull', 'ZipCode', 'Country', 'CountryFull', 'Birthday', 'Age', 'Occupation', 'Company', 'Vehicle', 'Latitude', 'Longitude'],
#     dependents=['GeoAreaKey', 'StartDT', 'EndDT', 'Continent', 'Gender', 'Title', 'GivenName', 'MiddleInitial', 'Surname', 'StreetAddress', 'City', 'State', 'StateFull', 'ZipCode', 'Country', 'CountryFull', 'Birthday', 'Age', 'Occupation', 'Company', 'Vehicle', 'Latitude', 'Longitude'],
#     stratum=None)
# 23 grouped branch(es) UNION ALL'd; a branch reports max(count(DISTINCT b)) per
# dependent b, and b is determined by a when that max is 1.
--   →
--   determinants: 23
--   dependents: 23
--   dependences_found: 13
--   Continent:
--   - Country
--   - CountryFull
--   - GeoAreaKey
--   - Longitude
--   - StateFull
--   Country:
--   - CountryFull
--   - GeoAreaKey
--   - StateFull
--   CountryFull:
--   - Country
--   - GeoAreaKey
--   - StateFull
--   GeoAreaKey:
--   - StateFull
--   State:
--   - StateFull

-- ── ADMIT/product ─────────────────────────────────────────────────────────────────────────
SELECT 'ALL' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "Price") AS dv
      FROM main.product GROUP BY "ProductKey")
UNION ALL
SELECT 'ProductKey' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "Price") AS dv
      FROM main.product)
ORDER BY 1;
--   →
--   - disagree: 0
--     groups: 2517
--     omitted: ALL
--     split: 0
--   - disagree: 1
--     groups: 1
--     omitted: ProductKey
--     split: 1

-- ── DEPEND/product ────────────────────────────────────────────────────────────────────────
# generated by mac_admit_identity.dependence_sql(
#     relation='main.product',
#     determinants=['Manufacturer', 'Brand', 'Color', 'WeightUnit', 'Weight', 'Cost', 'Price', 'CategoryKey', 'CategoryName', 'SubCategoryKey', 'SubCategoryName'],
#     dependents=['Manufacturer', 'Brand', 'Color', 'WeightUnit', 'Weight', 'Cost', 'Price', 'CategoryKey', 'CategoryName', 'SubCategoryKey', 'SubCategoryName'],
#     stratum=None)
# 11 grouped branch(es) UNION ALL'd; a branch reports max(count(DISTINCT b)) per
# dependent b, and b is determined by a when that max is 1.
--   →
--   determinants: 11
--   dependents: 11
--   dependences_found: 10
--   Brand:
--   - Manufacturer
--   CategoryKey:
--   - CategoryName
--   - SubCategoryKey
--   - SubCategoryName
--   CategoryName:
--   - CategoryKey
--   - SubCategoryKey
--   - SubCategoryName
--   Manufacturer:
--   - Brand
--   SubCategoryKey:
--   - SubCategoryName
--   SubCategoryName:
--   - SubCategoryKey

-- ── ADMIT/store ───────────────────────────────────────────────────────────────────────────
SELECT 'ALL' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "SquareMeters") AS dv
      FROM main.store GROUP BY "StoreKey")
UNION ALL
SELECT 'StoreKey' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "SquareMeters") AS dv
      FROM main.store)
ORDER BY 1;
--   →
--   - disagree: 0
--     groups: 74
--     omitted: ALL
--     split: 0
--   - disagree: 1
--     groups: 1
--     omitted: StoreKey
--     split: 1

-- ── DEPEND/store ──────────────────────────────────────────────────────────────────────────
# generated by mac_admit_identity.dependence_sql(
#     relation='main.store',
#     determinants=['StoreCode', 'GeoAreaKey', 'CountryCode', 'CountryName', 'State', 'OpenDate', 'CloseDate', 'Description', 'SquareMeters', 'Status'],
#     dependents=['StoreCode', 'GeoAreaKey', 'CountryCode', 'CountryName', 'State', 'OpenDate', 'CloseDate', 'Description', 'SquareMeters', 'Status'],
#     stratum=None)
# 10 grouped branch(es) UNION ALL'd; a branch reports max(count(DISTINCT b)) per
# dependent b, and b is determined by a when that max is 1.
--   →
--   determinants: 10
--   dependents: 10
--   dependences_found: 22
--   CountryCode:
--   - CountryName
--   - Description
--   - GeoAreaKey
--   - State
--   - StoreCode
--   CountryName:
--   - CountryCode
--   - Description
--   - GeoAreaKey
--   - State
--   - StoreCode
--   Description:
--   - GeoAreaKey
--   - State
--   - StoreCode
--   GeoAreaKey:
--   - Description
--   - State
--   - StoreCode
--   State:
--   - Description
--   - GeoAreaKey
--   - StoreCode
--   StoreCode:
--   - Description
--   - GeoAreaKey
--   - State

-- ── ADMIT/date ────────────────────────────────────────────────────────────────────────────
SELECT 'ALL' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "YearMonth") AS dv
      FROM main.date GROUP BY "Date")
UNION ALL
SELECT 'Date' AS omitted,
       count(*) AS groups,
       sum(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS split,
       sum(CASE WHEN dv > 1 THEN 1 ELSE 0 END) AS disagree
FROM (SELECT count(*) AS n, count(DISTINCT "YearMonth") AS dv
      FROM main.date)
ORDER BY 1;
--   →
--   - disagree: 0
--     groups: 4018
--     omitted: ALL
--     split: 0
--   - disagree: 1
--     groups: 1
--     omitted: Date
--     split: 1

-- ── DEPEND/date ───────────────────────────────────────────────────────────────────────────
# generated by mac_admit_identity.dependence_sql(
#     relation='main.date',
#     determinants=['Year', 'YearQuarter', 'YearQuarterNumber', 'Quarter', 'YearMonth', 'YearMonthShort', 'YearMonthNumber', 'Month', 'MonthShort', 'MonthNumber', 'DayofWeek', 'DayofWeekShort', 'DayofWeekNumber', 'WorkingDay', 'WorkingDayNumber'],
#     dependents=['Year', 'YearQuarter', 'YearQuarterNumber', 'Quarter', 'YearMonth', 'YearMonthShort', 'YearMonthNumber', 'Month', 'MonthShort', 'MonthNumber', 'DayofWeek', 'DayofWeekShort', 'DayofWeekNumber', 'WorkingDay', 'WorkingDayNumber'],
#     stratum=None)
# 15 grouped branch(es) UNION ALL'd; a branch reports max(count(DISTINCT b)) per
# dependent b, and b is determined by a when that max is 1.
--   →
--   determinants: 15
--   dependents: 15
--   dependences_found: 48
--   DayofWeek:
--   - DayofWeekNumber
--   - DayofWeekShort
--   DayofWeekNumber:
--   - DayofWeek
--   - DayofWeekShort
--   DayofWeekShort:
--   - DayofWeek
--   - DayofWeekNumber
--   Month:
--   - MonthNumber
--   - MonthShort
--   - YearMonth
--   - YearMonthNumber
--   - YearMonthShort
--   MonthNumber:
--   - Month
--   - MonthShort
--   - YearMonth
--   - YearMonthNumber
--   - YearMonthShort
--   MonthShort:
--   - Month
--   - MonthNumber
--   - YearMonth
--   - YearMonthNumber
--   - YearMonthShort
--   Quarter:
--   - Month
--   - MonthNumber
--   - MonthShort
--   - YearMonth
--   - YearMonthNumber
--   - YearMonthShort
--   - YearQuarter
--   - YearQuarterNumber
--   Year:
--   - YearMonth
--   - YearMonthNumber
--   - YearMonthShort
--   - YearQuarter
--   - YearQuarterNumber
--   YearMonth:
--   - YearMonthNumber
--   - YearMonthShort
--   YearMonthNumber:
--   - YearMonth
--   - YearMonthShort
--   YearMonthShort:
--   - YearMonth
--   - YearMonthNumber
--   YearQuarter:
--   - YearMonth
--   - YearMonthNumber
--   - YearMonthShort
--   - YearQuarterNumber
--   YearQuarterNumber:
--   - YearMonth
--   - YearMonthNumber
--   - YearMonthShort
--   - YearQuarter

-- ── G1/orderrows ──────────────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), coalesce(CAST("OrderKey" AS varchar), chr(2)), coalesce(CAST("RowNumber" AS varchar), chr(2)))) AS distinct_keys, count(*) - count(DISTINCT concat_ws(chr(1), coalesce(CAST("OrderKey" AS varchar), chr(2)), coalesce(CAST("RowNumber" AS varchar), chr(2)))) AS duplicate_rows
FROM main.orderrows;
--   →
--   - distinct_keys: 223974
--     duplicate_rows: 0
--     rows: 223974

-- ── G11/orderrows ─────────────────────────────────────────────────────────────────────────
SELECT count(*) - count("OrderKey") AS nulls_in_OrderKey, count(*) - count("RowNumber") AS nulls_in_RowNumber
FROM main.orderrows;
--   →
--   - nulls_in_OrderKey: 0
--     nulls_in_RowNumber: 0

-- ── G1/sales ──────────────────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), coalesce(CAST("OrderKey" AS varchar), chr(2)), coalesce(CAST("LineNumber" AS varchar), chr(2)))) AS distinct_keys, count(*) - count(DISTINCT concat_ws(chr(1), coalesce(CAST("OrderKey" AS varchar), chr(2)), coalesce(CAST("LineNumber" AS varchar), chr(2)))) AS duplicate_rows
FROM main.sales;
--   →
--   - distinct_keys: 223974
--     duplicate_rows: 0
--     rows: 223974

-- ── G11/sales ─────────────────────────────────────────────────────────────────────────────
SELECT count(*) - count("OrderKey") AS nulls_in_OrderKey, count(*) - count("LineNumber") AS nulls_in_LineNumber
FROM main.sales;
--   →
--   - nulls_in_LineNumber: 0
--     nulls_in_OrderKey: 0

-- ── G1/currencyexchange ───────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), coalesce(CAST("Date" AS varchar), chr(2)), coalesce(CAST("ToCurrency" AS varchar), chr(2)), coalesce(CAST("FromCurrency" AS varchar), chr(2)))) AS distinct_keys, count(*) - count(DISTINCT concat_ws(chr(1), coalesce(CAST("Date" AS varchar), chr(2)), coalesce(CAST("ToCurrency" AS varchar), chr(2)), coalesce(CAST("FromCurrency" AS varchar), chr(2)))) AS duplicate_rows
FROM main.currencyexchange;
--   →
--   - distinct_keys: 100450
--     duplicate_rows: 0
--     rows: 100450

-- ── G11/currencyexchange ──────────────────────────────────────────────────────────────────
SELECT count(*) - count("Date") AS nulls_in_Date, count(*) - count("ToCurrency") AS nulls_in_ToCurrency, count(*) - count("FromCurrency") AS nulls_in_FromCurrency
FROM main.currencyexchange;
--   →
--   - nulls_in_Date: 0
--     nulls_in_FromCurrency: 0
--     nulls_in_ToCurrency: 0

-- ── G1/orders ─────────────────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), coalesce(CAST("OrderKey" AS varchar), chr(2)))) AS distinct_keys, count(*) - count(DISTINCT concat_ws(chr(1), coalesce(CAST("OrderKey" AS varchar), chr(2)))) AS duplicate_rows
FROM main.orders;
--   →
--   - distinct_keys: 93470
--     duplicate_rows: 0
--     rows: 93470

-- ── G11/orders ────────────────────────────────────────────────────────────────────────────
SELECT count(*) - count("OrderKey") AS nulls_in_OrderKey
FROM main.orders;
--   →
--   - nulls_in_OrderKey: 0

-- ── G1/customer ───────────────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), coalesce(CAST("CustomerKey" AS varchar), chr(2)))) AS distinct_keys, count(*) - count(DISTINCT concat_ws(chr(1), coalesce(CAST("CustomerKey" AS varchar), chr(2)))) AS duplicate_rows
FROM main.customer;
--   →
--   - distinct_keys: 104990
--     duplicate_rows: 0
--     rows: 104990

-- ── G11/customer ──────────────────────────────────────────────────────────────────────────
SELECT count(*) - count("CustomerKey") AS nulls_in_CustomerKey
FROM main.customer;
--   →
--   - nulls_in_CustomerKey: 0

-- ── G1/product ────────────────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), coalesce(CAST("ProductKey" AS varchar), chr(2)))) AS distinct_keys, count(*) - count(DISTINCT concat_ws(chr(1), coalesce(CAST("ProductKey" AS varchar), chr(2)))) AS duplicate_rows
FROM main.product;
--   →
--   - distinct_keys: 2517
--     duplicate_rows: 0
--     rows: 2517

-- ── G11/product ───────────────────────────────────────────────────────────────────────────
SELECT count(*) - count("ProductKey") AS nulls_in_ProductKey
FROM main.product;
--   →
--   - nulls_in_ProductKey: 0

-- ── G1/store ──────────────────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), coalesce(CAST("StoreKey" AS varchar), chr(2)))) AS distinct_keys, count(*) - count(DISTINCT concat_ws(chr(1), coalesce(CAST("StoreKey" AS varchar), chr(2)))) AS duplicate_rows
FROM main.store;
--   →
--   - distinct_keys: 74
--     duplicate_rows: 0
--     rows: 74

-- ── G11/store ─────────────────────────────────────────────────────────────────────────────
SELECT count(*) - count("StoreKey") AS nulls_in_StoreKey
FROM main.store;
--   →
--   - nulls_in_StoreKey: 0

-- ── G1/date ───────────────────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), coalesce(CAST("Date" AS varchar), chr(2)))) AS distinct_keys, count(*) - count(DISTINCT concat_ws(chr(1), coalesce(CAST("Date" AS varchar), chr(2)))) AS duplicate_rows
FROM main.date;
--   →
--   - distinct_keys: 4018
--     duplicate_rows: 0
--     rows: 4018

-- ── G11/date ──────────────────────────────────────────────────────────────────────────────
SELECT count(*) - count("Date") AS nulls_in_Date
FROM main.date;
--   →
--   - nulls_in_Date: 0

-- ── G13/orderrows-within-key-dependence ───────────────────────────────────────────────────
# generated by mac_admit_identity.dependence_sql(
#     relation='main.orderrows',
#     determinants=['OrderKey', 'RowNumber'],
#     dependents=['OrderKey', 'RowNumber'],
#     stratum=None)
# 2 grouped branch(es) UNION ALL'd; a branch reports max(count(DISTINCT b)) per
# dependent b, and b is determined by a when that max is 1.
--   →
--   determinants: 2
--   dependents: 2
--   dependences_found: 0
--   (no single-column determinant for any dependent)

-- ── G13/sales-within-key-dependence ───────────────────────────────────────────────────────
# generated by mac_admit_identity.dependence_sql(
#     relation='main.sales',
#     determinants=['OrderKey', 'LineNumber'],
#     dependents=['OrderKey', 'LineNumber'],
#     stratum=None)
# 2 grouped branch(es) UNION ALL'd; a branch reports max(count(DISTINCT b)) per
# dependent b, and b is determined by a when that max is 1.
--   →
--   determinants: 2
--   dependents: 2
--   dependences_found: 0
--   (no single-column determinant for any dependent)

-- ── G13/currencyexchange-within-key-dependence ────────────────────────────────────────────
# generated by mac_admit_identity.dependence_sql(
#     relation='main.currencyexchange',
#     determinants=['Date', 'ToCurrency', 'FromCurrency'],
#     dependents=['Date', 'ToCurrency', 'FromCurrency'],
#     stratum=None)
# 3 grouped branch(es) UNION ALL'd; a branch reports max(count(DISTINCT b)) per
# dependent b, and b is determined by a when that max is 1.
--   →
--   determinants: 3
--   dependents: 3
--   dependences_found: 0
--   (no single-column determinant for any dependent)

-- ── G2/orderrows-product-substitutable ────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), OrderKey, ProductKey)) AS distinct_order_product, count(*) - count(DISTINCT concat_ws(chr(1), OrderKey, ProductKey)) AS rows_sharing_order_and_product
FROM main.orderrows;
--   →
--   - distinct_order_product: 223713
--     rows: 223974
--     rows_sharing_order_and_product: 261

-- ── G14/orderrows-repeated-product-lines-differ ───────────────────────────────────────────
SELECT count(*) AS colliding_groups, sum(CASE WHEN identical THEN 1 ELSE 0 END) AS groups_agreeing_on_every_figure, sum(CASE WHEN identical THEN 0 ELSE 1 END) AS groups_differing
FROM (
  SELECT OrderKey, ProductKey,
         (count(DISTINCT concat_ws(chr(1), Quantity, UnitPrice, NetPrice, UnitCost)) = 1) AS identical
  FROM main.orderrows GROUP BY OrderKey, ProductKey HAVING count(*) > 1);
--   →
--   - colliding_groups: 260
--     groups_agreeing_on_every_figure: 7
--     groups_differing: 253

-- ── G14b/orderrows-indistinguishable-line-rows ────────────────────────────────────────────
SELECT count(*) AS rows_in_agreeing_groups
FROM main.orderrows r
WHERE (r.OrderKey, r.ProductKey) IN (
  SELECT OrderKey, ProductKey FROM main.orderrows
  GROUP BY OrderKey, ProductKey
  HAVING count(*) > 1 AND count(DISTINCT concat_ws(chr(1), Quantity, UnitPrice, NetPrice, UnitCost)) = 1);
--   →
--   - rows_in_agreeing_groups: 14

-- ── G3/same-line-population ───────────────────────────────────────────────────────────────
SELECT (SELECT count(*) FROM (SELECT OrderKey, RowNumber FROM main.orderrows EXCEPT SELECT OrderKey, LineNumber FROM main.sales)) AS in_orderrows_not_sales,
       (SELECT count(*) FROM (SELECT OrderKey, LineNumber FROM main.sales EXCEPT SELECT OrderKey, RowNumber FROM main.orderrows)) AS in_sales_not_orderrows;
--   →
--   - in_orderrows_not_sales: 0
--     in_sales_not_orderrows: 0

-- ── G4/orders-natural-key ─────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), CustomerKey, StoreKey, DT, DeliveryDate, CurrencyCode)) AS distinct_header_tuples
FROM main.orders;
--   →
--   - distinct_header_tuples: 93467
--     rows: 93470

-- ── G5/product-alternate-keys ─────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT ProductKey) AS d_key, count(DISTINCT ProductCode) AS d_code, count(DISTINCT ProductName) AS d_name, count(DISTINCT concat_ws(chr(1), ProductKey, ProductCode)) AS d_key_code
FROM main.product;
--   →
--   - d_code: 2517
--     d_key: 2517
--     d_key_code: 2517
--     d_name: 2517
--     rows: 2517

-- ── G6/store-natural-temporal-key ─────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT StoreKey) AS d_storekey, count(DISTINCT StoreCode) AS d_storecode, count(DISTINCT concat_ws(chr(1), StoreCode, OpenDate)) AS d_code_opendate
FROM main.store;
--   →
--   - d_code_opendate: 74
--     d_storecode: 67
--     d_storekey: 74
--     rows: 74

-- ── G6b/store-versions-per-code ───────────────────────────────────────────────────────────
SELECT StoreCode, count(*) AS versions, min(OpenDate) AS first_open, max(OpenDate) AS last_open
FROM main.store GROUP BY StoreCode HAVING count(*) > 1 ORDER BY StoreCode;
--   →
--   - StoreCode: 3
--     first_open: '2012-01-07 00:00:00'
--     last_open: '2015-12-08 00:00:00'
--     versions: 2
--   - StoreCode: 7
--     first_open: '2007-05-07 00:00:00'
--     last_open: '2018-06-02 00:00:00'
--     versions: 3
--   - StoreCode: 25
--     first_open: '2010-01-01 00:00:00'
--     last_open: '2015-08-08 00:00:00'
--     versions: 2
--   - StoreCode: 46
--     first_open: '2012-08-08 00:00:00'
--     last_open: '2015-06-06 00:00:00'
--     versions: 2
--   - StoreCode: 58
--     first_open: '2007-07-08 00:00:00'
--     last_open: '2015-12-15 00:00:00'
--     versions: 2
--   - StoreCode: 60
--     first_open: '2005-04-04 00:00:00'
--     last_open: '2014-06-03 00:00:00'
--     versions: 2

-- ── G7/customer-person-duplicates ─────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT concat_ws(chr(1), GivenName, MiddleInitial, Surname, Birthday, StreetAddress, ZipCode)) AS distinct_persons
FROM main.customer;
--   →
--   - distinct_persons: 104990
--     rows: 104990

-- ── G8/date-key-bijection ─────────────────────────────────────────────────────────────────
SELECT count(*) AS rows, count(DISTINCT Date) AS d_date, count(DISTINCT DateKey) AS d_datekey, count(DISTINCT concat_ws(chr(1), Date, DateKey)) AS d_pair
FROM main.date;
--   →
--   - d_date: 4018
--     d_datekey: 4018
--     d_pair: 4018
--     rows: 4018

-- ── G9/fx-self-pairs-agree ────────────────────────────────────────────────────────────────
SELECT (FromCurrency = ToCurrency) AS self_pair, count(*) AS quotes, count(DISTINCT Exchange) AS distinct_rates
FROM main.currencyexchange GROUP BY 1 ORDER BY 1;
--   →
--   - distinct_rates: 31512
--     quotes: 80360
--     self_pair: false
--   - distinct_rates: 1
--     quotes: 20090
--     self_pair: true

-- ── G10/vintage-hints (offline, check_grain_declaration.cycle_hints()) ────────────────────
# not SQL: every declared key column tested against the gate's own hint list
--   →
--   hints_available: 8
--   keys_tested: 8
--   key_columns_tested: 12
--   republication_columns_in_a_key: 0

