-- queries/p4_transformation_authoring.sql
-- P4 · transformation-authoring — every query this step used to decide WHICH RULE each
-- measured defect gets (and which gets none), each written above the answer it returned.
-- Read-only over contoso.duckdb; the six CREATE OR REPLACE VIEW statements were AUTHORED,
-- never executed (connection.yaml declares read_only: true), so each SELECT body below is
-- the body of the view file it was written from.
-- generated by scratchpad/ingest/p4_transforms.py at 2026-09-18T09:15:10 · DuckDB 1.5.5

-- ================================================================================================
-- T1a · the served shape of contoso_served.v_contoso_order_line — column names and types the body produces (compared to data/datasets/v_contoso_order_line.yaml below)
DESCRIBE SELECT r."OrderKey",
       r."RowNumber",
       o."DT" AS OrderDate,
       o."DeliveryDate",
       o."CustomerKey",
       o."StoreKey",
       r."ProductKey",
       o."CurrencyCode",
       r."Quantity",
       r."UnitPrice",
       r."NetPrice",
       r."UnitCost"
FROM main.orderrows r
JOIN main.orders o ON o."OrderKey" = r."OrderKey";

--   ANSWER: column_name | column_type | null | key | default | extra
--           OrderKey | BIGINT | YES | NULL | NULL | NULL
--           RowNumber | INTEGER | YES | NULL | NULL | NULL
--           OrderDate | TIMESTAMP | YES | NULL | NULL | NULL
--           DeliveryDate | TIMESTAMP | YES | NULL | NULL | NULL
--           CustomerKey | INTEGER | YES | NULL | NULL | NULL
--           StoreKey | INTEGER | YES | NULL | NULL | NULL
--           ProductKey | INTEGER | YES | NULL | NULL | NULL
--           CurrencyCode | VARCHAR | YES | NULL | NULL | NULL
--           Quantity | INTEGER | YES | NULL | NULL | NULL
--           UnitPrice | DECIMAL(20,5) | YES | NULL | NULL | NULL
--           NetPrice | DECIMAL(20,5) | YES | NULL | NULL | NULL
--           UnitCost | DECIMAL(20,5) | YES | NULL | NULL | NULL

-- ================================================================================================
-- T1b · the served shape of contoso_served.dim_contoso_product — column names and types the body produces (compared to data/datasets/dim_contoso_product.yaml below)
DESCRIBE WITH color_spelling AS (                 -- how often each SPELLING of a colour is used
    SELECT "Color" AS color_raw, count(*) AS rows_with_spelling
    FROM main.product
    WHERE "Color" IS NOT NULL
    GROUP BY 1
),
color_canon AS (                         -- one canonical spelling per case-insensitive colour
    SELECT lower(color_raw) AS color_lc, color_raw AS color_canonical
    FROM (SELECT color_raw,
                 row_number() OVER (PARTITION BY lower(color_raw)
                                    ORDER BY rows_with_spelling DESC, color_raw) AS rn
          FROM color_spelling)
    WHERE rn = 1
)
SELECT p."ProductKey",
       p."ProductCode",
       p."ProductName",
       p."Manufacturer",
       p."Brand",
       coalesce(cc.color_canonical, p."Color") AS Color,
       nullif(p."WeightUnit", '') AS WeightUnit,
       p."Weight",
       p."Cost",
       p."Price",
       p."CategoryKey",
       p."CategoryName",
       p."SubCategoryKey",
       p."SubCategoryName"
FROM main.product p
LEFT JOIN color_canon cc ON cc.color_lc = lower(p."Color");

--   ANSWER: column_name | column_type | null | key | default | extra
--           ProductKey | INTEGER | YES | NULL | NULL | NULL
--           ProductCode | VARCHAR | YES | NULL | NULL | NULL
--           ProductName | VARCHAR | YES | NULL | NULL | NULL
--           Manufacturer | VARCHAR | YES | NULL | NULL | NULL
--           Brand | VARCHAR | YES | NULL | NULL | NULL
--           Color | VARCHAR | YES | NULL | NULL | NULL
--           WeightUnit | VARCHAR | YES | NULL | NULL | NULL
--           Weight | DECIMAL(20,5) | YES | NULL | NULL | NULL
--           Cost | DECIMAL(20,5) | YES | NULL | NULL | NULL
--           Price | DECIMAL(20,5) | YES | NULL | NULL | NULL
--           CategoryKey | INTEGER | YES | NULL | NULL | NULL
--           CategoryName | VARCHAR | YES | NULL | NULL | NULL
--           SubCategoryKey | INTEGER | YES | NULL | NULL | NULL
--           SubCategoryName | VARCHAR | YES | NULL | NULL | NULL

-- ================================================================================================
-- T1c · the served shape of contoso_served.dim_contoso_store — column names and types the body produces (compared to data/datasets/dim_contoso_store.yaml below)
DESCRIBE SELECT s."StoreKey",
       s."StoreCode",
       s."GeoAreaKey",
       s."CountryCode",
       s."CountryName",
       s."State",
       s."Description",
       s."OpenDate",
       s."CloseDate",
       s."SquareMeters",
       nullif(s."Status", '') AS Status
FROM main.store s;

--   ANSWER: column_name | column_type | null | key | default | extra
--           StoreKey | INTEGER | YES | NULL | NULL | NULL
--           StoreCode | INTEGER | YES | NULL | NULL | NULL
--           GeoAreaKey | INTEGER | YES | NULL | NULL | NULL
--           CountryCode | VARCHAR | YES | NULL | NULL | NULL
--           CountryName | VARCHAR | YES | NULL | NULL | NULL
--           State | VARCHAR | YES | NULL | NULL | NULL
--           Description | VARCHAR | YES | NULL | NULL | NULL
--           OpenDate | TIMESTAMP | YES | NULL | NULL | NULL
--           CloseDate | TIMESTAMP | YES | NULL | NULL | NULL
--           SquareMeters | INTEGER | YES | NULL | NULL | NULL
--           Status | VARCHAR | YES | NULL | NULL | NULL

-- ================================================================================================
-- T1d · the served shape of contoso_served.dim_contoso_customer — column names and types the body produces (compared to data/datasets/dim_contoso_customer.yaml below)
DESCRIBE SELECT c."CustomerKey",
       c."GeoAreaKey",
       c."StartDT",
       c."EndDT",
       c."Continent",
       c."CountryFull",
       c."Country",
       trim(c."StateFull") AS StateFull,
       trim(c."State") AS State,
       c."City",
       c."ZipCode",
       c."Gender"
FROM main.customer c;

--   ANSWER: column_name | column_type | null | key | default | extra
--           CustomerKey | INTEGER | YES | NULL | NULL | NULL
--           GeoAreaKey | INTEGER | YES | NULL | NULL | NULL
--           StartDT | TIMESTAMP | YES | NULL | NULL | NULL
--           EndDT | TIMESTAMP | YES | NULL | NULL | NULL
--           Continent | VARCHAR | YES | NULL | NULL | NULL
--           CountryFull | VARCHAR | YES | NULL | NULL | NULL
--           Country | VARCHAR | YES | NULL | NULL | NULL
--           StateFull | VARCHAR | YES | NULL | NULL | NULL
--           State | VARCHAR | YES | NULL | NULL | NULL
--           City | VARCHAR | YES | NULL | NULL | NULL
--           ZipCode | VARCHAR | YES | NULL | NULL | NULL
--           Gender | VARCHAR | YES | NULL | NULL | NULL

-- ================================================================================================
-- T1e · the served shape of contoso_served.dim_contoso_calendar_day — column names and types the body produces (compared to data/datasets/dim_contoso_calendar_day.yaml below)
DESCRIBE SELECT d."Date",
       d."DateKey",
       d."Year",
       d."YearQuarter",
       d."YearQuarterNumber",
       d."Quarter",
       d."YearMonth",
       d."YearMonthShort",
       d."YearMonthNumber",
       d."Month",
       d."MonthShort",
       d."MonthNumber",
       d."DayofWeek",
       d."DayofWeekShort",
       d."DayofWeekNumber",
       d."WorkingDay",
       d."WorkingDayNumber"
FROM main.date d;

--   ANSWER: column_name | column_type | null | key | default | extra
--           Date | TIMESTAMP | YES | NULL | NULL | NULL
--           DateKey | VARCHAR | YES | NULL | NULL | NULL
--           Year | INTEGER | YES | NULL | NULL | NULL
--           YearQuarter | VARCHAR | YES | NULL | NULL | NULL
--           YearQuarterNumber | INTEGER | YES | NULL | NULL | NULL
--           Quarter | VARCHAR | YES | NULL | NULL | NULL
--           YearMonth | VARCHAR | YES | NULL | NULL | NULL
--           YearMonthShort | VARCHAR | YES | NULL | NULL | NULL
--           YearMonthNumber | INTEGER | YES | NULL | NULL | NULL
--           Month | VARCHAR | YES | NULL | NULL | NULL
--           MonthShort | VARCHAR | YES | NULL | NULL | NULL
--           MonthNumber | INTEGER | YES | NULL | NULL | NULL
--           DayofWeek | VARCHAR | YES | NULL | NULL | NULL
--           DayofWeekShort | VARCHAR | YES | NULL | NULL | NULL
--           DayofWeekNumber | INTEGER | YES | NULL | NULL | NULL
--           WorkingDay | INTEGER | YES | NULL | NULL | NULL
--           WorkingDayNumber | INTEGER | YES | NULL | NULL | NULL

-- ================================================================================================
-- T1f · the served shape of contoso_served.v_contoso_fx_rate_day — column names and types the body produces (compared to data/datasets/v_contoso_fx_rate_day.yaml below)
DESCRIBE SELECT x."Date",
       x."FromCurrency",
       x."ToCurrency",
       x."Exchange"
FROM main.currencyexchange x;

--   ANSWER: column_name | column_type | null | key | default | extra
--           Date | TIMESTAMP | YES | NULL | NULL | NULL
--           FromCurrency | VARCHAR | YES | NULL | NULL | NULL
--           ToCurrency | VARCHAR | YES | NULL | NULL | NULL
--           Exchange | DECIMAL(20,5) | YES | NULL | NULL | NULL

-- ================================================================================================
-- T2a · the grain of contoso_served.v_contoso_order_line: rows, distinct cell keys, duplicate keys, null key parts
SELECT count(*) AS served_rows,
       count(DISTINCT ("OrderKey", "RowNumber")) AS distinct_keys,
       count(*) - count(DISTINCT ("OrderKey", "RowNumber")) AS duplicate_keys,
       count(*) FILTER (WHERE "OrderKey" IS NULL) + count(*) FILTER (WHERE "RowNumber" IS NULL) AS null_key_parts
FROM (
SELECT r."OrderKey",
       r."RowNumber",
       o."DT" AS OrderDate,
       o."DeliveryDate",
       o."CustomerKey",
       o."StoreKey",
       r."ProductKey",
       o."CurrencyCode",
       r."Quantity",
       r."UnitPrice",
       r."NetPrice",
       r."UnitCost"
FROM main.orderrows r
JOIN main.orders o ON o."OrderKey" = r."OrderKey"
) t;

--   ANSWER: served_rows | distinct_keys | duplicate_keys | null_key_parts
--           223974 | 223974 | 0 | 0

-- ================================================================================================
-- T2b · the grain of contoso_served.dim_contoso_product: rows, distinct cell keys, duplicate keys, null key parts
SELECT count(*) AS served_rows,
       count(DISTINCT "ProductKey") AS distinct_keys,
       count(*) - count(DISTINCT "ProductKey") AS duplicate_keys,
       count(*) FILTER (WHERE "ProductKey" IS NULL) AS null_key_parts
FROM (
WITH color_spelling AS (                 -- how often each SPELLING of a colour is used
    SELECT "Color" AS color_raw, count(*) AS rows_with_spelling
    FROM main.product
    WHERE "Color" IS NOT NULL
    GROUP BY 1
),
color_canon AS (                         -- one canonical spelling per case-insensitive colour
    SELECT lower(color_raw) AS color_lc, color_raw AS color_canonical
    FROM (SELECT color_raw,
                 row_number() OVER (PARTITION BY lower(color_raw)
                                    ORDER BY rows_with_spelling DESC, color_raw) AS rn
          FROM color_spelling)
    WHERE rn = 1
)
SELECT p."ProductKey",
       p."ProductCode",
       p."ProductName",
       p."Manufacturer",
       p."Brand",
       coalesce(cc.color_canonical, p."Color") AS Color,
       nullif(p."WeightUnit", '') AS WeightUnit,
       p."Weight",
       p."Cost",
       p."Price",
       p."CategoryKey",
       p."CategoryName",
       p."SubCategoryKey",
       p."SubCategoryName"
FROM main.product p
LEFT JOIN color_canon cc ON cc.color_lc = lower(p."Color")
) t;

--   ANSWER: served_rows | distinct_keys | duplicate_keys | null_key_parts
--           2517 | 2517 | 0 | 0

-- ================================================================================================
-- T2c · the grain of contoso_served.dim_contoso_store: rows, distinct cell keys, duplicate keys, null key parts
SELECT count(*) AS served_rows,
       count(DISTINCT "StoreKey") AS distinct_keys,
       count(*) - count(DISTINCT "StoreKey") AS duplicate_keys,
       count(*) FILTER (WHERE "StoreKey" IS NULL) AS null_key_parts
FROM (
SELECT s."StoreKey",
       s."StoreCode",
       s."GeoAreaKey",
       s."CountryCode",
       s."CountryName",
       s."State",
       s."Description",
       s."OpenDate",
       s."CloseDate",
       s."SquareMeters",
       nullif(s."Status", '') AS Status
FROM main.store s
) t;

--   ANSWER: served_rows | distinct_keys | duplicate_keys | null_key_parts
--           74 | 74 | 0 | 0

-- ================================================================================================
-- T2d · the grain of contoso_served.dim_contoso_customer: rows, distinct cell keys, duplicate keys, null key parts
SELECT count(*) AS served_rows,
       count(DISTINCT "CustomerKey") AS distinct_keys,
       count(*) - count(DISTINCT "CustomerKey") AS duplicate_keys,
       count(*) FILTER (WHERE "CustomerKey" IS NULL) AS null_key_parts
FROM (
SELECT c."CustomerKey",
       c."GeoAreaKey",
       c."StartDT",
       c."EndDT",
       c."Continent",
       c."CountryFull",
       c."Country",
       trim(c."StateFull") AS StateFull,
       trim(c."State") AS State,
       c."City",
       c."ZipCode",
       c."Gender"
FROM main.customer c
) t;

--   ANSWER: served_rows | distinct_keys | duplicate_keys | null_key_parts
--           104990 | 104990 | 0 | 0

-- ================================================================================================
-- T2e · the grain of contoso_served.dim_contoso_calendar_day: rows, distinct cell keys, duplicate keys, null key parts
SELECT count(*) AS served_rows,
       count(DISTINCT "Date") AS distinct_keys,
       count(*) - count(DISTINCT "Date") AS duplicate_keys,
       count(*) FILTER (WHERE "Date" IS NULL) AS null_key_parts
FROM (
SELECT d."Date",
       d."DateKey",
       d."Year",
       d."YearQuarter",
       d."YearQuarterNumber",
       d."Quarter",
       d."YearMonth",
       d."YearMonthShort",
       d."YearMonthNumber",
       d."Month",
       d."MonthShort",
       d."MonthNumber",
       d."DayofWeek",
       d."DayofWeekShort",
       d."DayofWeekNumber",
       d."WorkingDay",
       d."WorkingDayNumber"
FROM main.date d
) t;

--   ANSWER: served_rows | distinct_keys | duplicate_keys | null_key_parts
--           4018 | 4018 | 0 | 0

-- ================================================================================================
-- T2f · the grain of contoso_served.v_contoso_fx_rate_day: rows, distinct cell keys, duplicate keys, null key parts
SELECT count(*) AS served_rows,
       count(DISTINCT ("Date", "FromCurrency", "ToCurrency")) AS distinct_keys,
       count(*) - count(DISTINCT ("Date", "FromCurrency", "ToCurrency")) AS duplicate_keys,
       count(*) FILTER (WHERE "Date" IS NULL) + count(*) FILTER (WHERE "FromCurrency" IS NULL) + count(*) FILTER (WHERE "ToCurrency" IS NULL) AS null_key_parts
FROM (
SELECT x."Date",
       x."FromCurrency",
       x."ToCurrency",
       x."Exchange"
FROM main.currencyexchange x
) t;

--   ANSWER: served_rows | distinct_keys | duplicate_keys | null_key_parts
--           100450 | 100450 | 0 | 0

-- ================================================================================================
-- T3 · the header/detail join: is it lossless and fan-out free? (orphan lines, headers without lines, unique header key)
SELECT (SELECT count(*) FROM main.orderrows)                                   AS detail_rows,
       (SELECT count(*) FROM main.orders)                                      AS header_rows,
       (SELECT count(DISTINCT "OrderKey") FROM main.orders)                    AS distinct_header_keys,
       (SELECT count(*) FROM main.orderrows r
         WHERE NOT EXISTS (SELECT 1 FROM main.orders o WHERE o."OrderKey" = r."OrderKey"))
                                                                               AS orphan_lines,
       (SELECT count(*) FROM main.orders o
         WHERE NOT EXISTS (SELECT 1 FROM main.orderrows r WHERE r."OrderKey" = o."OrderKey"))
                                                                               AS headers_without_lines;

--   ANSWER: detail_rows | header_rows | distinct_header_keys | orphan_lines | headers_without_lines
--           223974 | 93470 | 93470 | 0 | 0

-- ================================================================================================
-- T4 · the rename orders.DT -> OrderDate: is it the same value the sales delivery already calls OrderDate, on every line?
SELECT count(*) AS lines_compared,
       count(*) FILTER (WHERE o."DT" <> s."OrderDate") AS differing_values,
       count(*) FILTER (WHERE o."DT" IS NULL OR s."OrderDate" IS NULL) AS nulls_either_side
FROM main.orderrows r
JOIN main.orders o ON o."OrderKey" = r."OrderKey"
JOIN main.sales  s ON s."OrderKey" = r."OrderKey" AND s."LineNumber" = r."RowNumber";

--   ANSWER: lines_compared | differing_values | nulls_either_side
--           223974 | 0 | 0

-- ================================================================================================
-- T5 · duplicate_delivery: does main.sales repeat the served line, value for value? (the defect the transform dissolves by not reading it)
SELECT count(*)                                                      AS matched_lines,
       count(*) FILTER (WHERE s."ProductKey"   <> r."ProductKey")     AS diff_product,
       count(*) FILTER (WHERE s."Quantity"     <> r."Quantity")       AS diff_qty,
       count(*) FILTER (WHERE s."UnitPrice"    <> r."UnitPrice")      AS diff_unitprice,
       count(*) FILTER (WHERE s."NetPrice"     <> r."NetPrice")       AS diff_netprice,
       count(*) FILTER (WHERE s."UnitCost"     <> r."UnitCost")       AS diff_unitcost,
       count(*) FILTER (WHERE s."CustomerKey"  <> o."CustomerKey")    AS diff_customer,
       count(*) FILTER (WHERE s."StoreKey"     <> o."StoreKey")       AS diff_store,
       count(*) FILTER (WHERE s."OrderDate"    <> o."DT")             AS diff_orderdate,
       count(*) FILTER (WHERE s."DeliveryDate" <> o."DeliveryDate")   AS diff_delivery,
       count(*) FILTER (WHERE s."CurrencyCode" <> o."CurrencyCode")   AS diff_currency,
       count(*) FILTER (WHERE s."ExchangeRate" <> f."Exchange")       AS diff_fx_vs_quote
FROM main.orderrows r
JOIN main.orders o ON o."OrderKey" = r."OrderKey"
JOIN main.sales  s ON s."OrderKey" = r."OrderKey" AND s."LineNumber" = r."RowNumber"
JOIN main.currencyexchange f ON f."Date" = o."DT" AND f."FromCurrency" = 'USD'
                            AND f."ToCurrency" = o."CurrencyCode";

--   ANSWER: matched_lines | diff_product | diff_qty | diff_unitprice | diff_netprice | diff_unitcost | diff_customer | diff_store | diff_orderdate | diff_delivery | diff_currency | diff_fx_vs_quote
--           223974 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0

-- ================================================================================================
-- T6a · case_variant_vocabulary: the Color spellings, and which case-insensitive group carries more than one
SELECT count(DISTINCT "Color")                             AS spellings,
       count(DISTINCT lower("Color"))                      AS colours,
       count(*) FILTER (WHERE "Color" IS NULL)             AS null_colours,
       count(*) FILTER (WHERE "Color" LIKE '% %')          AS multi_word_spellings,
       (SELECT count(*) FROM (SELECT lower("Color") FROM main.product
                              GROUP BY 1 HAVING count(DISTINCT "Color") > 1)) AS split_groups
FROM main.product;

--   ANSWER: spellings | colours | null_colours | multi_word_spellings | split_groups
--           17 | 16 | 0 | 14 | 1

-- ================================================================================================
-- T6b · the split group, spelled out with its row counts (the majority spelling is what the rule keeps)
SELECT "Color" AS spelling, count(*) AS rows_with_spelling
FROM main.product
WHERE lower("Color") IN (SELECT lower("Color") FROM main.product
                         GROUP BY 1 HAVING count(DISTINCT "Color") > 1)
GROUP BY 1 ORDER BY rows_with_spelling DESC;

--   ANSWER: spelling | rows_with_spelling
--           Blue | 197
--           blue | 3

-- ================================================================================================
-- T6c · the rule's own effect: is color_canon one row per colour (no fan-out), how many product rows change spelling, and how many spellings survive?
WITH color_spelling AS (
    SELECT "Color" AS color_raw, count(*) AS rows_with_spelling
    FROM main.product WHERE "Color" IS NOT NULL GROUP BY 1
),
color_canon AS (
    SELECT lower(color_raw) AS color_lc, color_raw AS color_canonical
    FROM (SELECT color_raw,
                 row_number() OVER (PARTITION BY lower(color_raw)
                                    ORDER BY rows_with_spelling DESC, color_raw) AS rn
          FROM color_spelling)
    WHERE rn = 1
)
SELECT (SELECT count(*) FROM color_canon)                                  AS canon_rows,
       (SELECT count(DISTINCT color_lc) FROM color_canon)                  AS canon_distinct_keys,
       count(*)                                                            AS product_rows_out,
       count(*) FILTER (WHERE cc.color_canonical <> p."Color")             AS rows_respelled,
       count(DISTINCT coalesce(cc.color_canonical, p."Color"))             AS served_spellings
FROM main.product p LEFT JOIN color_canon cc ON cc.color_lc = lower(p."Color");

--   ANSWER: canon_rows | canon_distinct_keys | product_rows_out | rows_respelled | served_spellings
--           16 | 16 | 2517 | 3 | 16

-- ================================================================================================
-- T7 · absence_semantics in product.WeightUnit: how missing is spelled in the landing, what the rule leaves, and the 62 rows it does NOT fix
SELECT count(*)                                                                AS product_rows,
       count(*) FILTER (WHERE "WeightUnit" = '')                               AS unit_empty_string,
       count(*) FILTER (WHERE "WeightUnit" IS NULL)                            AS unit_null_in_landing,
       count(*) FILTER (WHERE nullif("WeightUnit", '') IS NULL)                AS unit_missing_served,
       count(DISTINCT nullif("WeightUnit", ''))                                AS unit_values_served,
       count(*) FILTER (WHERE "Weight" IS NULL)                                AS weight_null,
       count(*) FILTER (WHERE "Weight" IS NULL AND "WeightUnit" <> '')         AS unit_without_weight,
       count(*) FILTER (WHERE "Weight" IS NOT NULL AND "WeightUnit" = '')      AS weight_without_unit
FROM main.product;

--   ANSWER: product_rows | unit_empty_string | unit_null_in_landing | unit_missing_served | unit_values_served | weight_null | unit_without_weight | weight_without_unit
--           2517 | 222 | 0 | 222 | 3 | 284 | 62 | 0

-- ================================================================================================
-- T8 · absence_semantics in store.Status: the two spellings of missing, what the rule leaves, and the row that argues against reading '' as 'operating'
SELECT count(*)                                                             AS store_rows,
       count(*) FILTER (WHERE "Status" = '')                                AS status_empty_string,
       count(*) FILTER (WHERE "Status" IS NULL)                             AS status_null_in_landing,
       count(*) FILTER (WHERE nullif("Status", '') IS NULL)                 AS status_missing_served,
       count(DISTINCT nullif("Status", ''))                                 AS status_values_served,
       count(*) FILTER (WHERE "Status" = '' AND "CloseDate" IS NOT NULL)    AS blank_status_with_closedate,
       count(*) FILTER (WHERE "Status" <> '' AND "CloseDate" IS NULL)       AS named_status_without_closedate
FROM main.store;

--   ANSWER: store_rows | status_empty_string | status_null_in_landing | status_missing_served | status_values_served | blank_status_with_closedate | named_status_without_closedate
--           74 | 58 | 1 | 59 | 2 | 1 | 0

-- ================================================================================================
-- T9 · empty-string sweep over all 33 (landing relation, served text column) pairs — which served text columns spell missing as ''?
SELECT * FROM (
  SELECT 'orders.CurrencyCode' AS served_text_column, count(*) AS n FROM main.orders WHERE "CurrencyCode" = ''
  UNION ALL SELECT 'product.ProductCode' AS served_text_column, count(*) AS n FROM main.product WHERE "ProductCode" = ''
  UNION ALL SELECT 'product.ProductName' AS served_text_column, count(*) AS n FROM main.product WHERE "ProductName" = ''
  UNION ALL SELECT 'product.Manufacturer' AS served_text_column, count(*) AS n FROM main.product WHERE "Manufacturer" = ''
  UNION ALL SELECT 'product.Brand' AS served_text_column, count(*) AS n FROM main.product WHERE "Brand" = ''
  UNION ALL SELECT 'product.Color' AS served_text_column, count(*) AS n FROM main.product WHERE "Color" = ''
  UNION ALL SELECT 'product.WeightUnit' AS served_text_column, count(*) AS n FROM main.product WHERE "WeightUnit" = ''
  UNION ALL SELECT 'product.CategoryName' AS served_text_column, count(*) AS n FROM main.product WHERE "CategoryName" = ''
  UNION ALL SELECT 'product.SubCategoryName' AS served_text_column, count(*) AS n FROM main.product WHERE "SubCategoryName" = ''
  UNION ALL SELECT 'store.CountryCode' AS served_text_column, count(*) AS n FROM main.store WHERE "CountryCode" = ''
  UNION ALL SELECT 'store.CountryName' AS served_text_column, count(*) AS n FROM main.store WHERE "CountryName" = ''
  UNION ALL SELECT 'store.State' AS served_text_column, count(*) AS n FROM main.store WHERE "State" = ''
  UNION ALL SELECT 'store.Description' AS served_text_column, count(*) AS n FROM main.store WHERE "Description" = ''
  UNION ALL SELECT 'store.Status' AS served_text_column, count(*) AS n FROM main.store WHERE "Status" = ''
  UNION ALL SELECT 'customer.Continent' AS served_text_column, count(*) AS n FROM main.customer WHERE "Continent" = ''
  UNION ALL SELECT 'customer.CountryFull' AS served_text_column, count(*) AS n FROM main.customer WHERE "CountryFull" = ''
  UNION ALL SELECT 'customer.Country' AS served_text_column, count(*) AS n FROM main.customer WHERE "Country" = ''
  UNION ALL SELECT 'customer.StateFull' AS served_text_column, count(*) AS n FROM main.customer WHERE "StateFull" = ''
  UNION ALL SELECT 'customer.State' AS served_text_column, count(*) AS n FROM main.customer WHERE "State" = ''
  UNION ALL SELECT 'customer.City' AS served_text_column, count(*) AS n FROM main.customer WHERE "City" = ''
  UNION ALL SELECT 'customer.ZipCode' AS served_text_column, count(*) AS n FROM main.customer WHERE "ZipCode" = ''
  UNION ALL SELECT 'customer.Gender' AS served_text_column, count(*) AS n FROM main.customer WHERE "Gender" = ''
  UNION ALL SELECT 'date.DateKey' AS served_text_column, count(*) AS n FROM main.date WHERE "DateKey" = ''
  UNION ALL SELECT 'date.YearQuarter' AS served_text_column, count(*) AS n FROM main.date WHERE "YearQuarter" = ''
  UNION ALL SELECT 'date.Quarter' AS served_text_column, count(*) AS n FROM main.date WHERE "Quarter" = ''
  UNION ALL SELECT 'date.YearMonth' AS served_text_column, count(*) AS n FROM main.date WHERE "YearMonth" = ''
  UNION ALL SELECT 'date.YearMonthShort' AS served_text_column, count(*) AS n FROM main.date WHERE "YearMonthShort" = ''
  UNION ALL SELECT 'date.Month' AS served_text_column, count(*) AS n FROM main.date WHERE "Month" = ''
  UNION ALL SELECT 'date.MonthShort' AS served_text_column, count(*) AS n FROM main.date WHERE "MonthShort" = ''
  UNION ALL SELECT 'date.DayofWeek' AS served_text_column, count(*) AS n FROM main.date WHERE "DayofWeek" = ''
  UNION ALL SELECT 'date.DayofWeekShort' AS served_text_column, count(*) AS n FROM main.date WHERE "DayofWeekShort" = ''
  UNION ALL SELECT 'currencyexchange.FromCurrency' AS served_text_column, count(*) AS n FROM main.currencyexchange WHERE "FromCurrency" = ''
  UNION ALL SELECT 'currencyexchange.ToCurrency' AS served_text_column, count(*) AS n FROM main.currencyexchange WHERE "ToCurrency" = ''
) WHERE n > 0 ORDER BY n DESC;

--   ANSWER: served_text_column | n
--           product.WeightUnit | 222
--           store.Status | 58

-- ================================================================================================
-- T10 · whitespace sweep over the same 33 pairs — is any served text value padded (i.e. does any column need a trim the transforms do not write)?
SELECT * FROM (
  SELECT 'orders.CurrencyCode' AS served_text_column, count(*) AS n FROM main.orders WHERE "CurrencyCode" <> trim("CurrencyCode")
  UNION ALL SELECT 'product.ProductCode' AS served_text_column, count(*) AS n FROM main.product WHERE "ProductCode" <> trim("ProductCode")
  UNION ALL SELECT 'product.ProductName' AS served_text_column, count(*) AS n FROM main.product WHERE "ProductName" <> trim("ProductName")
  UNION ALL SELECT 'product.Manufacturer' AS served_text_column, count(*) AS n FROM main.product WHERE "Manufacturer" <> trim("Manufacturer")
  UNION ALL SELECT 'product.Brand' AS served_text_column, count(*) AS n FROM main.product WHERE "Brand" <> trim("Brand")
  UNION ALL SELECT 'product.Color' AS served_text_column, count(*) AS n FROM main.product WHERE "Color" <> trim("Color")
  UNION ALL SELECT 'product.WeightUnit' AS served_text_column, count(*) AS n FROM main.product WHERE "WeightUnit" <> trim("WeightUnit")
  UNION ALL SELECT 'product.CategoryName' AS served_text_column, count(*) AS n FROM main.product WHERE "CategoryName" <> trim("CategoryName")
  UNION ALL SELECT 'product.SubCategoryName' AS served_text_column, count(*) AS n FROM main.product WHERE "SubCategoryName" <> trim("SubCategoryName")
  UNION ALL SELECT 'store.CountryCode' AS served_text_column, count(*) AS n FROM main.store WHERE "CountryCode" <> trim("CountryCode")
  UNION ALL SELECT 'store.CountryName' AS served_text_column, count(*) AS n FROM main.store WHERE "CountryName" <> trim("CountryName")
  UNION ALL SELECT 'store.State' AS served_text_column, count(*) AS n FROM main.store WHERE "State" <> trim("State")
  UNION ALL SELECT 'store.Description' AS served_text_column, count(*) AS n FROM main.store WHERE "Description" <> trim("Description")
  UNION ALL SELECT 'store.Status' AS served_text_column, count(*) AS n FROM main.store WHERE "Status" <> trim("Status")
  UNION ALL SELECT 'customer.Continent' AS served_text_column, count(*) AS n FROM main.customer WHERE "Continent" <> trim("Continent")
  UNION ALL SELECT 'customer.CountryFull' AS served_text_column, count(*) AS n FROM main.customer WHERE "CountryFull" <> trim("CountryFull")
  UNION ALL SELECT 'customer.Country' AS served_text_column, count(*) AS n FROM main.customer WHERE "Country" <> trim("Country")
  UNION ALL SELECT 'customer.StateFull' AS served_text_column, count(*) AS n FROM main.customer WHERE "StateFull" <> trim("StateFull")
  UNION ALL SELECT 'customer.State' AS served_text_column, count(*) AS n FROM main.customer WHERE "State" <> trim("State")
  UNION ALL SELECT 'customer.City' AS served_text_column, count(*) AS n FROM main.customer WHERE "City" <> trim("City")
  UNION ALL SELECT 'customer.ZipCode' AS served_text_column, count(*) AS n FROM main.customer WHERE "ZipCode" <> trim("ZipCode")
  UNION ALL SELECT 'customer.Gender' AS served_text_column, count(*) AS n FROM main.customer WHERE "Gender" <> trim("Gender")
  UNION ALL SELECT 'date.DateKey' AS served_text_column, count(*) AS n FROM main.date WHERE "DateKey" <> trim("DateKey")
  UNION ALL SELECT 'date.YearQuarter' AS served_text_column, count(*) AS n FROM main.date WHERE "YearQuarter" <> trim("YearQuarter")
  UNION ALL SELECT 'date.Quarter' AS served_text_column, count(*) AS n FROM main.date WHERE "Quarter" <> trim("Quarter")
  UNION ALL SELECT 'date.YearMonth' AS served_text_column, count(*) AS n FROM main.date WHERE "YearMonth" <> trim("YearMonth")
  UNION ALL SELECT 'date.YearMonthShort' AS served_text_column, count(*) AS n FROM main.date WHERE "YearMonthShort" <> trim("YearMonthShort")
  UNION ALL SELECT 'date.Month' AS served_text_column, count(*) AS n FROM main.date WHERE "Month" <> trim("Month")
  UNION ALL SELECT 'date.MonthShort' AS served_text_column, count(*) AS n FROM main.date WHERE "MonthShort" <> trim("MonthShort")
  UNION ALL SELECT 'date.DayofWeek' AS served_text_column, count(*) AS n FROM main.date WHERE "DayofWeek" <> trim("DayofWeek")
  UNION ALL SELECT 'date.DayofWeekShort' AS served_text_column, count(*) AS n FROM main.date WHERE "DayofWeekShort" <> trim("DayofWeekShort")
  UNION ALL SELECT 'currencyexchange.FromCurrency' AS served_text_column, count(*) AS n FROM main.currencyexchange WHERE "FromCurrency" <> trim("FromCurrency")
  UNION ALL SELECT 'currencyexchange.ToCurrency' AS served_text_column, count(*) AS n FROM main.currencyexchange WHERE "ToCurrency" <> trim("ToCurrency")
) WHERE n > 0 ORDER BY n DESC;

--   ANSWER: served_text_column | n
--           customer.State | 4
--           customer.StateFull | 4

-- ================================================================================================
-- T11a · UNFIXED · line numbering: does RowNumber start at 0, and how many orders have gaps?
SELECT count(*)                                                        AS orders_with_lines,
       count(*) FILTER (WHERE min_rn <> 0)                             AS orders_not_starting_at_zero,
       count(*) FILTER (WHERE max_rn + 1 <> n_lines)                   AS orders_with_gaps
FROM (SELECT "OrderKey", min("RowNumber") AS min_rn, max("RowNumber") AS max_rn, count(*) AS n_lines
      FROM main.orderrows GROUP BY 1);

--   ANSWER: orders_with_lines | orders_not_starting_at_zero | orders_with_gaps
--           93470 | 0 | 1448

-- ================================================================================================
-- T11b · UNFIXED · the indistinguishable lines: ROW PAIRS that agree on the order, the product and all four figures (this is NOT P2's G14, which asked a different question — see T11b2)
SELECT count(*) AS groups, sum(n) AS rows_in_those_groups, max(n) AS largest_group
FROM (SELECT "OrderKey", "ProductKey", "Quantity", "UnitPrice", "NetPrice", "UnitCost", count(*) AS n
      FROM main.orderrows GROUP BY 1,2,3,4,5,6 HAVING count(*) > 1);

--   ANSWER: groups | rows_in_those_groups | largest_group
--           8 | 16 | 2

-- ================================================================================================
-- T11b2 · the same defect counted P2's way (whole (OrderKey, ProductKey) group agrees), and the group-size split that reconciles 7/14 with T11b's 8/16
SELECT (SELECT count(*) FROM (SELECT "OrderKey","ProductKey" FROM main.orderrows GROUP BY 1,2
          HAVING count(*) > 1 AND count(DISTINCT ("Quantity","UnitPrice","NetPrice","UnitCost")) = 1))
                                                                       AS p2_g14_groups_all_rows_agree,
       (SELECT count(*) FROM (SELECT "OrderKey","ProductKey" FROM main.orderrows GROUP BY 1,2
          HAVING count(*) > 1))                                        AS colliding_key_groups,
       (SELECT count(*) FROM (SELECT "OrderKey","ProductKey" FROM main.orderrows GROUP BY 1,2
          HAVING count(*) = 3))                                        AS groups_of_three_rows;

--   ANSWER: p2_g14_groups_all_rows_agree | colliding_key_groups | groups_of_three_rows
--           7 | 260 | 1

-- ================================================================================================
-- T11c · UNFIXED · the sentinel store: its values, and how much of the fact points at it
SELECT (SELECT count(*) FROM main.store WHERE "StoreKey" = 999999)                AS sentinel_rows,
       (SELECT "StoreCode"   FROM main.store WHERE "StoreKey" = 999999)           AS sentinel_storecode,
       (SELECT "GeoAreaKey"  FROM main.store WHERE "StoreKey" = 999999)           AS sentinel_geoareakey,
       (SELECT "CountryCode" FROM main.store WHERE "StoreKey" = 999999)           AS sentinel_countrycode,
       (SELECT "CountryName" FROM main.store WHERE "StoreKey" = 999999)           AS sentinel_countryname,
       (SELECT "State"       FROM main.store WHERE "StoreKey" = 999999)           AS sentinel_state,
       (SELECT count(*) FROM main.orderrows r JOIN main.orders o USING ("OrderKey")
         WHERE o."StoreKey" = 999999)                                             AS lines_on_sentinel,
       (SELECT count(*) FROM main.orderrows)                                      AS lines_total;

--   ANSWER: sentinel_rows | sentinel_storecode | sentinel_geoareakey | sentinel_countrycode | sentinel_countryname | sentinel_state | lines_on_sentinel | lines_total
--           1 | -1 | -1 | -- | Online | Online | 93550 | 223974

-- ================================================================================================
-- T11d · UNFIXED · GeoAreaKey: is there anything in this warehouse to resolve it against?
SELECT (SELECT count(DISTINCT "GeoAreaKey") FROM main.customer)                   AS geo_in_customer,
       (SELECT count(DISTINCT "GeoAreaKey") FROM main.store)                      AS geo_in_store,
       (SELECT count(*) FROM (SELECT DISTINCT "GeoAreaKey" FROM main.store
                              EXCEPT SELECT "GeoAreaKey" FROM main.customer))     AS store_geo_not_in_customer,
       (SELECT count(*) FROM information_schema.tables
         WHERE table_schema = 'main' AND lower(table_name) LIKE '%geo%')          AS geography_relations;

--   ANSWER: geo_in_customer | geo_in_store | store_geo_not_in_customer | geography_relations
--           608 | 67 | 4 | 0

-- ================================================================================================
-- T11e · UNFIXED-BY-EXCLUSION · customer.Age: what year is it as-of, and is it served?
SELECT count(*)                                                        AS customer_rows,
       count(DISTINCT year("Birthday") + "Age")                        AS distinct_asof_years,
       min(year("Birthday") + "Age")                                   AS asof_min,
       max(year("Birthday") + "Age")                                   AS asof_max,
       (SELECT max(year("DT")) FROM main.orders)                        AS last_order_year,
       count(*) FILTER (WHERE "StartDT" = "EndDT")                     AS zero_length_validity_windows
FROM main.customer;

--   ANSWER: customer_rows | distinct_asof_years | asof_min | asof_max | last_order_year | zero_length_validity_windows
--           104990 | 2 | 2020 | 2021 | 2025 | 1

-- ================================================================================================
-- T11f · UNFIXED · the calendar's reach past the facts, and the two type mismatches it carries
SELECT (SELECT count(*) FROM main.date)                                           AS calendar_days,
       (SELECT count(*) FROM main.date d
         WHERE d."Date" > (SELECT max("DeliveryDate") FROM main.orders))           AS days_after_last_fact,
       (SELECT count(*) FROM main.date d
         WHERE NOT EXISTS (SELECT 1 FROM main.orders o WHERE o."DT" = d."Date"))   AS days_with_no_order,
       (SELECT count(DISTINCT "WorkingDay") FROM main.date)                        AS workingday_values,
       (SELECT min("WorkingDay") FROM main.date)                                   AS workingday_min,
       (SELECT max("WorkingDay") FROM main.date)                                   AS workingday_max,
       (SELECT min("DateKey") FROM main.date)                                      AS datekey_min,
       (SELECT max("DateKey") FROM main.date)                                      AS datekey_max;

--   ANSWER: calendar_days | days_after_last_fact | days_with_no_order | workingday_values | workingday_min | workingday_max | datekey_min | datekey_max
--           4018 | 359 | 568 | 2 | 0 | 1 | 20160101 | 20261231

-- ================================================================================================
-- T11g · UNFIXED · store versioning: codes, versions, and codes carrying more than one version
SELECT count(*)                                              AS store_rows,
       count(DISTINCT "StoreCode")                           AS store_codes,
       (SELECT count(*) FROM (SELECT "StoreCode" FROM main.store
                              GROUP BY 1 HAVING count(*) > 1)) AS codes_with_versions,
       (SELECT max(n) FROM (SELECT count(*) AS n FROM main.store GROUP BY "StoreCode")) AS max_versions_per_code
FROM main.store;

--   ANSWER: store_rows | store_codes | codes_with_versions | max_versions_per_code
--           74 | 67 | 6 | 3

-- ================================================================================================
-- T13a · padded_label: which region labels carry whitespace, how many spellings that costs, and whether the trimmed form already exists as its own value
SELECT (SELECT count(*) FROM main.customer WHERE "State" <> trim("State"))          AS state_padded_rows,
       (SELECT count(*) FROM main.customer WHERE "StateFull" <> trim("StateFull"))  AS statefull_padded_rows,
       (SELECT count(DISTINCT "State") FROM main.customer)                          AS state_spellings,
       (SELECT count(DISTINCT trim("State")) FROM main.customer)                    AS state_spellings_trimmed,
       (SELECT count(DISTINCT "StateFull") FROM main.customer)                      AS statefull_spellings,
       (SELECT count(DISTINCT trim("StateFull")) FROM main.customer)                AS statefull_spellings_trimmed;

--   ANSWER: state_padded_rows | statefull_padded_rows | state_spellings | state_spellings_trimmed | statefull_spellings | statefull_spellings_trimmed
--           4 | 4 | 565 | 563 | 610 | 608

-- ================================================================================================
-- T13b · the padded values spelled out beside their unpadded twins — same region or two regions? (GeoAreaKey / Country / Continent decide it)
SELECT "StateFull" AS statefull, "GeoAreaKey" AS geoareakey, "Country" AS country,
       "Continent" AS continent, count(*) AS n
FROM main.customer
WHERE trim("StateFull") IN (SELECT trim("StateFull") FROM main.customer
                            WHERE "StateFull" <> trim("StateFull"))
GROUP BY 1,2,3,4 ORDER BY 1,2;

--   ANSWER: statefull | geoareakey | country | continent | n
--           Birmingham | 93 | GB | Europe | 38
--           Birmingham  | 93 | GB | Europe | 3
--           Bradford | 102 | GB | Europe | 35
--           Bradford  | 102 | GB | Europe | 1

-- ================================================================================================
-- T13c · does the trim break the dependence P2 measured (StateFull -> State, GeoAreaKey, Country, Continent), and does the split reach the fact?
SELECT (SELECT count(*) FROM (SELECT "StateFull" FROM main.customer GROUP BY 1
          HAVING count(DISTINCT ("State","GeoAreaKey","Country","Continent")) > 1))
                                                                        AS violations_before_trim,
       (SELECT count(*) FROM (SELECT trim("StateFull") AS sf FROM main.customer GROUP BY 1
          HAVING count(DISTINCT (trim("State"),"GeoAreaKey","Country","Continent")) > 1))
                                                                        AS violations_after_trim,
       (SELECT count(*) FROM main.orderrows r JOIN main.orders o USING ("OrderKey")
          JOIN main.customer c USING ("CustomerKey")
         WHERE c."StateFull" <> trim(c."StateFull"))                    AS order_lines_affected;

--   ANSWER: violations_before_trim | violations_after_trim | order_lines_affected
--           0 | 0 | 13

-- ================================================================================================
-- T14 · UNFIXED/DISCLOSED · how much of each served dimension the fact never points at
SELECT (SELECT count(*) FROM main.customer)                                        AS customers,
       (SELECT count(*) FROM main.customer c WHERE NOT EXISTS
          (SELECT 1 FROM main.orders o WHERE o."CustomerKey" = c."CustomerKey"))    AS customers_never_ordering,
       (SELECT count(*) FROM main.store)                                           AS store_versions,
       (SELECT count(*) FROM main.store s WHERE NOT EXISTS
          (SELECT 1 FROM main.orders o WHERE o."StoreKey" = s."StoreKey"))          AS store_versions_never_selling;

--   ANSWER: customers | customers_never_ordering | store_versions | store_versions_never_selling
--           104990 | 52801 | 74 | 10

-- ================================================================================================
-- T12 · v_contoso_fx_rate_day needs no rule: is the grid complete, the self-rate exactly 1, every rate positive?
SELECT count(*)                                                          AS quote_rows,
       (SELECT count(*) FROM main.date) * count(DISTINCT "FromCurrency")
                                       * count(DISTINCT "ToCurrency")    AS complete_grid,
       count(*) FILTER (WHERE "FromCurrency" = "ToCurrency"
                          AND "Exchange" <> 1)                           AS self_rate_not_one,
       count(*) FILTER (WHERE "Exchange" <= 0)                           AS non_positive_rates,
       count(*) FILTER (WHERE "Exchange" IS NULL)                        AS null_rates
FROM main.currencyexchange;

--   ANSWER: quote_rows | complete_grid | self_rate_not_one | non_positive_rates | null_rates
--           100450 | 100450 | 0 | 0 | 0

