-- queries/p6_lookup_pre_resolution.sql — P6 · lookup-pre-resolution, EVERY measurement with
-- the answer it returned. Generated by scratchpad/ingest/p6_lookups.py; re-running it
-- reproduces this file and the registers byte-for-byte.
--
-- WHERE THESE RAN: connection.yaml declares read_only: true, so the six served views do not
-- exist in contoso.duckdb. They were materialised on a COPY of the warehouse in the
-- scratchpad by executing data/transforms/*.sql VERBATIM (the P4 dry-run pattern), every
-- query below ran against THOSE views, and the copy was deleted. Nothing was written to
-- contoso.duckdb. `main.*` in the L9 queries is the landing, read for comparison only.
-- Observed 2026-09-18. DuckDB 1.5.5.

-- ================================================================================================
-- L1 · the six served relations, materialised on the scratch copy from the authored transforms (the relations every register below is cut from)
-- ================================================================================================
SELECT table_name, (SELECT count(*) FROM information_schema.columns c WHERE c.table_schema='contoso_served' AND c.table_name=t.table_name) AS columns FROM information_schema.tables t WHERE table_schema='contoso_served' ORDER BY 1;
-- ANSWER:
-- dim_contoso_calendar_day   17
-- dim_contoso_customer   12
-- dim_contoso_product   14
-- dim_contoso_store   11
-- v_contoso_fx_rate_day   4
-- v_contoso_order_line   12

-- ================================================================================================
-- L1b · dim_contoso_calendar_day row count
-- ================================================================================================
SELECT count(*) FROM contoso_served.dim_contoso_calendar_day;
-- ANSWER:
-- 4018

-- ================================================================================================
-- L1b · dim_contoso_customer row count
-- ================================================================================================
SELECT count(*) FROM contoso_served.dim_contoso_customer;
-- ANSWER:
-- 104990

-- ================================================================================================
-- L1b · dim_contoso_product row count
-- ================================================================================================
SELECT count(*) FROM contoso_served.dim_contoso_product;
-- ANSWER:
-- 2517

-- ================================================================================================
-- L1b · dim_contoso_store row count
-- ================================================================================================
SELECT count(*) FROM contoso_served.dim_contoso_store;
-- ANSWER:
-- 74

-- ================================================================================================
-- L1b · v_contoso_fx_rate_day row count
-- ================================================================================================
SELECT count(*) FROM contoso_served.v_contoso_fx_rate_day;
-- ANSWER:
-- 100450

-- ================================================================================================
-- L1b · v_contoso_order_line row count
-- ================================================================================================
SELECT count(*) FROM contoso_served.v_contoso_order_line;
-- ANSWER:
-- 223974

-- ================================================================================================
-- L2 · dim_contoso_calendar_day: distinct values per column — the cardinality every register/no-register decision below is taken on
-- ================================================================================================
SELECT count(DISTINCT "Date") AS "Date", count(DISTINCT "DateKey") AS "DateKey", count(DISTINCT "Year") AS "Year", count(DISTINCT "YearQuarter") AS "YearQuarter", count(DISTINCT "YearQuarterNumber") AS "YearQuarterNumber", count(DISTINCT "Quarter") AS "Quarter", count(DISTINCT "YearMonth") AS "YearMonth", count(DISTINCT "YearMonthShort") AS "YearMonthShort", count(DISTINCT "YearMonthNumber") AS "YearMonthNumber", count(DISTINCT "Month") AS "Month", count(DISTINCT "MonthShort") AS "MonthShort", count(DISTINCT "MonthNumber") AS "MonthNumber", count(DISTINCT "DayofWeek") AS "DayofWeek", count(DISTINCT "DayofWeekShort") AS "DayofWeekShort", count(DISTINCT "DayofWeekNumber") AS "DayofWeekNumber", count(DISTINCT "WorkingDay") AS "WorkingDay", count(DISTINCT "WorkingDayNumber") AS "WorkingDayNumber" FROM contoso_served.dim_contoso_calendar_day;
-- ANSWER:
--    Date = 4018
--    DateKey = 4018
--    Year = 11
--    YearQuarter = 44
--    YearQuarterNumber = 44
--    Quarter = 4
--    YearMonth = 132
--    YearMonthShort = 132
--    YearMonthNumber = 132
--    Month = 12
--    MonthShort = 12
--    MonthNumber = 12
--    DayofWeek = 7
--    DayofWeekShort = 7
--    DayofWeekNumber = 7
--    WorkingDay = 2
--    WorkingDayNumber = 2761

-- ================================================================================================
-- L2b · dim_contoso_calendar_day: NULL rows per column
-- ================================================================================================
SELECT count(*) - count("Date") AS "Date", count(*) - count("DateKey") AS "DateKey", count(*) - count("Year") AS "Year", count(*) - count("YearQuarter") AS "YearQuarter", count(*) - count("YearQuarterNumber") AS "YearQuarterNumber", count(*) - count("Quarter") AS "Quarter", count(*) - count("YearMonth") AS "YearMonth", count(*) - count("YearMonthShort") AS "YearMonthShort", count(*) - count("YearMonthNumber") AS "YearMonthNumber", count(*) - count("Month") AS "Month", count(*) - count("MonthShort") AS "MonthShort", count(*) - count("MonthNumber") AS "MonthNumber", count(*) - count("DayofWeek") AS "DayofWeek", count(*) - count("DayofWeekShort") AS "DayofWeekShort", count(*) - count("DayofWeekNumber") AS "DayofWeekNumber", count(*) - count("WorkingDay") AS "WorkingDay", count(*) - count("WorkingDayNumber") AS "WorkingDayNumber" FROM contoso_served.dim_contoso_calendar_day;
-- ANSWER:
-- 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

-- ================================================================================================
-- L2 · dim_contoso_customer: distinct values per column — the cardinality every register/no-register decision below is taken on
-- ================================================================================================
SELECT count(DISTINCT "CustomerKey") AS "CustomerKey", count(DISTINCT "GeoAreaKey") AS "GeoAreaKey", count(DISTINCT "StartDT") AS "StartDT", count(DISTINCT "EndDT") AS "EndDT", count(DISTINCT "Continent") AS "Continent", count(DISTINCT "CountryFull") AS "CountryFull", count(DISTINCT "Country") AS "Country", count(DISTINCT "StateFull") AS "StateFull", count(DISTINCT "State") AS "State", count(DISTINCT "City") AS "City", count(DISTINCT "ZipCode") AS "ZipCode", count(DISTINCT "Gender") AS "Gender" FROM contoso_served.dim_contoso_customer;
-- ANSWER:
--    CustomerKey = 104990
--    GeoAreaKey = 608
--    StartDT = 11305
--    EndDT = 14711
--    Continent = 3
--    CountryFull = 8
--    Country = 8
--    StateFull = 608
--    State = 563
--    City = 34581
--    ZipCode = 40639
--    Gender = 2

-- ================================================================================================
-- L2b · dim_contoso_customer: NULL rows per column
-- ================================================================================================
SELECT count(*) - count("CustomerKey") AS "CustomerKey", count(*) - count("GeoAreaKey") AS "GeoAreaKey", count(*) - count("StartDT") AS "StartDT", count(*) - count("EndDT") AS "EndDT", count(*) - count("Continent") AS "Continent", count(*) - count("CountryFull") AS "CountryFull", count(*) - count("Country") AS "Country", count(*) - count("StateFull") AS "StateFull", count(*) - count("State") AS "State", count(*) - count("City") AS "City", count(*) - count("ZipCode") AS "ZipCode", count(*) - count("Gender") AS "Gender" FROM contoso_served.dim_contoso_customer;
-- ANSWER:
-- 0   0   0   0   0   0   0   0   0   0   0   0

-- ================================================================================================
-- L2 · dim_contoso_product: distinct values per column — the cardinality every register/no-register decision below is taken on
-- ================================================================================================
SELECT count(DISTINCT "ProductKey") AS "ProductKey", count(DISTINCT "ProductCode") AS "ProductCode", count(DISTINCT "ProductName") AS "ProductName", count(DISTINCT "Manufacturer") AS "Manufacturer", count(DISTINCT "Brand") AS "Brand", count(DISTINCT "Color") AS "Color", count(DISTINCT "WeightUnit") AS "WeightUnit", count(DISTINCT "Weight") AS "Weight", count(DISTINCT "Cost") AS "Cost", count(DISTINCT "Price") AS "Price", count(DISTINCT "CategoryKey") AS "CategoryKey", count(DISTINCT "CategoryName") AS "CategoryName", count(DISTINCT "SubCategoryKey") AS "SubCategoryKey", count(DISTINCT "SubCategoryName") AS "SubCategoryName" FROM contoso_served.dim_contoso_product;
-- ANSWER:
--    ProductKey = 2517
--    ProductCode = 2517
--    ProductName = 2517
--    Manufacturer = 11
--    Brand = 11
--    Color = 16
--    WeightUnit = 3
--    Weight = 296
--    Cost = 480
--    Price = 426
--    CategoryKey = 8
--    CategoryName = 8
--    SubCategoryKey = 32
--    SubCategoryName = 32

-- ================================================================================================
-- L2b · dim_contoso_product: NULL rows per column
-- ================================================================================================
SELECT count(*) - count("ProductKey") AS "ProductKey", count(*) - count("ProductCode") AS "ProductCode", count(*) - count("ProductName") AS "ProductName", count(*) - count("Manufacturer") AS "Manufacturer", count(*) - count("Brand") AS "Brand", count(*) - count("Color") AS "Color", count(*) - count("WeightUnit") AS "WeightUnit", count(*) - count("Weight") AS "Weight", count(*) - count("Cost") AS "Cost", count(*) - count("Price") AS "Price", count(*) - count("CategoryKey") AS "CategoryKey", count(*) - count("CategoryName") AS "CategoryName", count(*) - count("SubCategoryKey") AS "SubCategoryKey", count(*) - count("SubCategoryName") AS "SubCategoryName" FROM contoso_served.dim_contoso_product;
-- ANSWER:
-- 0   0   0   0   0   0   222   284   0   0   0   0   0   0

-- ================================================================================================
-- L2 · dim_contoso_store: distinct values per column — the cardinality every register/no-register decision below is taken on
-- ================================================================================================
SELECT count(DISTINCT "StoreKey") AS "StoreKey", count(DISTINCT "StoreCode") AS "StoreCode", count(DISTINCT "GeoAreaKey") AS "GeoAreaKey", count(DISTINCT "CountryCode") AS "CountryCode", count(DISTINCT "CountryName") AS "CountryName", count(DISTINCT "State") AS "State", count(DISTINCT "Description") AS "Description", count(DISTINCT "OpenDate") AS "OpenDate", count(DISTINCT "CloseDate") AS "CloseDate", count(DISTINCT "SquareMeters") AS "SquareMeters", count(DISTINCT "Status") AS "Status" FROM contoso_served.dim_contoso_store;
-- ANSWER:
--    StoreKey = 74
--    StoreCode = 67
--    GeoAreaKey = 67
--    CountryCode = 9
--    CountryName = 9
--    State = 67
--    Description = 67
--    OpenDate = 32
--    CloseDate = 15
--    SquareMeters = 39
--    Status = 2

-- ================================================================================================
-- L2b · dim_contoso_store: NULL rows per column
-- ================================================================================================
SELECT count(*) - count("StoreKey") AS "StoreKey", count(*) - count("StoreCode") AS "StoreCode", count(*) - count("GeoAreaKey") AS "GeoAreaKey", count(*) - count("CountryCode") AS "CountryCode", count(*) - count("CountryName") AS "CountryName", count(*) - count("State") AS "State", count(*) - count("Description") AS "Description", count(*) - count("OpenDate") AS "OpenDate", count(*) - count("CloseDate") AS "CloseDate", count(*) - count("SquareMeters") AS "SquareMeters", count(*) - count("Status") AS "Status" FROM contoso_served.dim_contoso_store;
-- ANSWER:
-- 0   0   0   0   0   0   0   0   58   1   59

-- ================================================================================================
-- L2 · v_contoso_fx_rate_day: distinct values per column — the cardinality every register/no-register decision below is taken on
-- ================================================================================================
SELECT count(DISTINCT "Date") AS "Date", count(DISTINCT "FromCurrency") AS "FromCurrency", count(DISTINCT "ToCurrency") AS "ToCurrency", count(DISTINCT "Exchange") AS "Exchange" FROM contoso_served.v_contoso_fx_rate_day;
-- ANSWER:
--    Date = 4018
--    FromCurrency = 5
--    ToCurrency = 5
--    Exchange = 31512

-- ================================================================================================
-- L2b · v_contoso_fx_rate_day: NULL rows per column
-- ================================================================================================
SELECT count(*) - count("Date") AS "Date", count(*) - count("FromCurrency") AS "FromCurrency", count(*) - count("ToCurrency") AS "ToCurrency", count(*) - count("Exchange") AS "Exchange" FROM contoso_served.v_contoso_fx_rate_day;
-- ANSWER:
-- 0   0   0   0

-- ================================================================================================
-- L2 · v_contoso_order_line: distinct values per column — the cardinality every register/no-register decision below is taken on
-- ================================================================================================
SELECT count(DISTINCT "OrderKey") AS "OrderKey", count(DISTINCT "RowNumber") AS "RowNumber", count(DISTINCT "OrderDate") AS "OrderDate", count(DISTINCT "DeliveryDate") AS "DeliveryDate", count(DISTINCT "CustomerKey") AS "CustomerKey", count(DISTINCT "StoreKey") AS "StoreKey", count(DISTINCT "ProductKey") AS "ProductKey", count(DISTINCT "CurrencyCode") AS "CurrencyCode", count(DISTINCT "Quantity") AS "Quantity", count(DISTINCT "UnitPrice") AS "UnitPrice", count(DISTINCT "NetPrice") AS "NetPrice", count(DISTINCT "UnitCost") AS "UnitCost" FROM contoso_served.v_contoso_order_line;
-- ANSWER:
--    OrderKey = 93470
--    RowNumber = 7
--    OrderDate = 3450
--    DeliveryDate = 3498
--    CustomerKey = 52189
--    StoreKey = 64
--    ProductKey = 2517
--    CurrencyCode = 5
--    Quantity = 10
--    UnitPrice = 1760
--    NetPrice = 18407
--    UnitCost = 1955

-- ================================================================================================
-- L2b · v_contoso_order_line: NULL rows per column
-- ================================================================================================
SELECT count(*) - count("OrderKey") AS "OrderKey", count(*) - count("RowNumber") AS "RowNumber", count(*) - count("OrderDate") AS "OrderDate", count(*) - count("DeliveryDate") AS "DeliveryDate", count(*) - count("CustomerKey") AS "CustomerKey", count(*) - count("StoreKey") AS "StoreKey", count(*) - count("ProductKey") AS "ProductKey", count(*) - count("CurrencyCode") AS "CurrencyCode", count(*) - count("Quantity") AS "Quantity", count(*) - count("UnitPrice") AS "UnitPrice", count(*) - count("NetPrice") AS "NetPrice", count(*) - count("UnitCost") AS "UnitCost" FROM contoso_served.v_contoso_order_line;
-- ANSWER:
-- 0   0   0   0   0   0   0   0   0   0   0   0

-- ================================================================================================
-- L3a · GeoAreaKey -> one StateFull / State / Country / CountryFull / Continent? (keys with more than one distinct value on the right)
-- ================================================================================================
SELECT count(*) FILTER (WHERE d_statefull > 1) AS geoarea_with_2_statefull, count(*) FILTER (WHERE d_state > 1) AS with_2_state, count(*) FILTER (WHERE d_country > 1) AS with_2_country, count(*) FILTER (WHERE d_countryfull > 1) AS with_2_countryfull, count(*) FILTER (WHERE d_continent > 1) AS with_2_continent, count(*) AS geoareas FROM (SELECT "GeoAreaKey", count(DISTINCT "StateFull") d_statefull, count(DISTINCT "State") d_state, count(DISTINCT "Country") d_country, count(DISTINCT "CountryFull") d_countryfull, count(DISTINCT "Continent") d_continent FROM contoso_served.dim_contoso_customer GROUP BY 1);
-- ANSWER:
-- 0   0   0   0   0   608

-- ================================================================================================
-- L3b · Country -> one CountryFull and one Continent?
-- ================================================================================================
SELECT count(*) AS countries, count(*) FILTER (WHERE d_full > 1) AS with_2_names, count(*) FILTER (WHERE d_cont > 1) AS with_2_continents FROM (SELECT "Country", count(DISTINCT "CountryFull") d_full, count(DISTINCT "Continent") d_cont FROM contoso_served.dim_contoso_customer GROUP BY 1);
-- ANSWER:
-- 8   0   0

-- ================================================================================================
-- L3c · CategoryKey -> one CategoryName, SubCategoryKey -> one SubCategoryName and one parent CategoryKey?
-- ================================================================================================
SELECT (SELECT count(*) FROM (SELECT "CategoryKey" FROM contoso_served.dim_contoso_product GROUP BY 1 HAVING count(DISTINCT "CategoryName") > 1)) AS cat_with_2_names, (SELECT count(*) FROM (SELECT "SubCategoryKey" FROM contoso_served.dim_contoso_product GROUP BY 1 HAVING count(DISTINCT "SubCategoryName") > 1)) AS sub_with_2_names, (SELECT count(*) FROM (SELECT "SubCategoryKey" FROM contoso_served.dim_contoso_product GROUP BY 1 HAVING count(DISTINCT "CategoryKey") > 1)) AS sub_with_2_parents;
-- ANSWER:
-- 0   0   0

-- ================================================================================================
-- L3d · Brand <-> Manufacturer: is either direction a function today?
-- ================================================================================================
SELECT (SELECT count(*) FROM (SELECT "Brand" FROM contoso_served.dim_contoso_product GROUP BY 1 HAVING count(DISTINCT "Manufacturer") > 1)) AS brand_with_2_manufacturers, (SELECT count(*) FROM (SELECT "Manufacturer" FROM contoso_served.dim_contoso_product GROUP BY 1 HAVING count(DISTINCT "Brand") > 1)) AS manufacturer_with_2_brands;
-- ANSWER:
-- 0   0

-- ================================================================================================
-- L3e · MonthNumber -> one Month/MonthShort/Quarter; DayofWeekNumber -> one DayofWeek/DayofWeekShort
-- ================================================================================================
SELECT (SELECT count(*) FROM (SELECT "MonthNumber" FROM contoso_served.dim_contoso_calendar_day GROUP BY 1 HAVING count(DISTINCT "Month") > 1 OR count(DISTINCT "MonthShort") > 1 OR count(DISTINCT "Quarter") > 1)) AS month_ambiguous, (SELECT count(*) FROM (SELECT "DayofWeekNumber" FROM contoso_served.dim_contoso_calendar_day GROUP BY 1 HAVING count(DISTINCT "DayofWeek") > 1 OR count(DISTINCT "DayofWeekShort") > 1)) AS weekday_ambiguous;
-- ANSWER:
-- 0   0

-- ================================================================================================
-- L4 · cut contoso_brand.lookup.csv from dim_contoso_product
-- ================================================================================================
SELECT "Brand" AS "Brand", "Brand" AS label, lower(trim("Brand")) AS search_key,
       "Manufacturer" AS manufacturer, 'dim_contoso_product' AS source_view, 'I' AS confidence,
       'value set measured on ' || count(*) || ' of 2517 served product rows' AS note
FROM contoso_served.dim_contoso_product
GROUP BY "Brand", "Manufacturer"
ORDER BY "Brand";
-- ANSWER:
-- A. Datum   A. Datum   a. datum   A. Datum Corporation   dim_contoso_product   I   value set measured on 132 of 2517 served product rows
-- Adventure Works   Adventure Works   adventure works   Adventure Works   dim_contoso_product   I   value set measured on 192 of 2517 served product rows
-- Contoso   Contoso   contoso   Contoso, Ltd   dim_contoso_product   I   value set measured on 710 of 2517 served product rows
-- Fabrikam   Fabrikam   fabrikam   Fabrikam, Inc.   dim_contoso_product   I   value set measured on 267 of 2517 served product rows
-- Litware   Litware   litware   Litware, Inc.   dim_contoso_product   I   value set measured on 264 of 2517 served product rows
-- Northwind Traders   Northwind Traders   northwind traders   Northwind Traders   dim_contoso_product   I   value set measured on 47 of 2517 served product rows
-- Proseware   Proseware   proseware   Proseware, Inc.   dim_contoso_product   I   value set measured on 244 of 2517 served product rows
-- Southridge Video   Southridge Video   southridge video   Southridge Video   dim_contoso_product   I   value set measured on 192 of 2517 served product rows
-- Tailspin Toys   Tailspin Toys   tailspin toys   Tailspin Toys   dim_contoso_product   I   value set measured on 144 of 2517 served product rows
-- The Phone Company   The Phone Company   the phone company   The Phone Company   dim_contoso_product   I   value set measured on 152 of 2517 served product rows
-- Wide World Importers   Wide World Importers   wide world importers   Wide World Importers   dim_contoso_product   I   value set measured on 173 of 2517 served product rows

-- ================================================================================================
-- L4 · cut contoso_color.lookup.csv from dim_contoso_product
-- ================================================================================================
SELECT "Color" AS "Color", "Color" AS label, lower(trim("Color")) AS search_key,
       'dim_contoso_product' AS source_view, 'I' AS confidence,
       'served rows with this colour: ' || count(*) AS note
FROM contoso_served.dim_contoso_product
WHERE "Color" IS NOT NULL
GROUP BY "Color"
ORDER BY "Color";
-- ANSWER:
-- Azure   Azure   azure   dim_contoso_product   I   served rows with this colour: 14
-- Black   Black   black   dim_contoso_product   I   served rows with this colour: 602
-- Blue   Blue   blue   dim_contoso_product   I   served rows with this colour: 200
-- Brown   Brown   brown   dim_contoso_product   I   served rows with this colour: 77
-- Gold   Gold   gold   dim_contoso_product   I   served rows with this colour: 50
-- Green   Green   green   dim_contoso_product   I   served rows with this colour: 74
-- Grey   Grey   grey   dim_contoso_product   I   served rows with this colour: 283
-- Orange   Orange   orange   dim_contoso_product   I   served rows with this colour: 55
-- Pink   Pink   pink   dim_contoso_product   I   served rows with this colour: 84
-- Purple   Purple   purple   dim_contoso_product   I   served rows with this colour: 6
-- Red   Red   red   dim_contoso_product   I   served rows with this colour: 99
-- Silver   Silver   silver   dim_contoso_product   I   served rows with this colour: 417
-- Silver Grey   Silver Grey   silver grey   dim_contoso_product   I   served rows with this colour: 14
-- Transparent   Transparent   transparent   dim_contoso_product   I   served rows with this colour: 1
-- White   White   white   dim_contoso_product   I   served rows with this colour: 505
-- Yellow   Yellow   yellow   dim_contoso_product   I   served rows with this colour: 36

-- ================================================================================================
-- L4 · cut contoso_product_category.lookup.csv from dim_contoso_product
-- ================================================================================================
SELECT "CategoryKey" AS "CategoryKey", "CategoryName" AS label,
       lower(trim("CategoryName")) AS search_key, 'dim_contoso_product' AS source_view, 'I' AS confidence,
       'served products in this category: ' || count(*) AS note
FROM contoso_served.dim_contoso_product
GROUP BY "CategoryKey", "CategoryName"
ORDER BY "CategoryKey";
-- ANSWER:
-- 1   Audio   audio   dim_contoso_product   I   served products in this category: 115
-- 2   TV and Video   tv and video   dim_contoso_product   I   served products in this category: 222
-- 3   Computers   computers   dim_contoso_product   I   served products in this category: 606
-- 4   Cameras and camcorders   cameras and camcorders   dim_contoso_product   I   served products in this category: 372
-- 5   Cell phones   cell phones   dim_contoso_product   I   served products in this category: 285
-- 6   Music, Movies and Audio Books   music, movies and audio books   dim_contoso_product   I   served products in this category: 90
-- 7   Games and Toys   games and toys   dim_contoso_product   I   served products in this category: 166
-- 8   Home Appliances   home appliances   dim_contoso_product   I   served products in this category: 661

-- ================================================================================================
-- L4 · cut contoso_product_subcategory.lookup.csv from dim_contoso_product
-- ================================================================================================
SELECT "SubCategoryKey" AS "SubCategoryKey", "SubCategoryName" AS label,
       lower(trim("SubCategoryName")) AS search_key, "CategoryKey" AS parent_category_key,
       'dim_contoso_product' AS source_view, 'I' AS confidence,
       'served products in this subcategory: ' || count(*) AS note
FROM contoso_served.dim_contoso_product
GROUP BY "SubCategoryKey", "SubCategoryName", "CategoryKey"
ORDER BY "SubCategoryKey";
-- ANSWER:
-- 101   MP4&MP3   mp4&mp3   1   dim_contoso_product   I   served products in this subcategory: 45
-- 104   Recording Pen   recording pen   1   dim_contoso_product   I   served products in this subcategory: 20
-- 106   Bluetooth Headphones   bluetooth headphones   1   dim_contoso_product   I   served products in this subcategory: 50
-- 201   Televisions   televisions   2   dim_contoso_product   I   served products in this subcategory: 50
-- 202   VCD & DVD   vcd & dvd   2   dim_contoso_product   I   served products in this subcategory: 26
-- 203   Home Theater System   home theater system   2   dim_contoso_product   I   served products in this subcategory: 100
-- 205   Car Video   car video   2   dim_contoso_product   I   served products in this subcategory: 46
-- 301   Laptops   laptops   3   dim_contoso_product   I   served products in this subcategory: 78
-- 303   Desktops   desktops   3   dim_contoso_product   I   served products in this subcategory: 45
-- 304   Monitors   monitors   3   dim_contoso_product   I   served products in this subcategory: 78
-- 305   Projectors & Screens   projectors & screens   3   dim_contoso_product   I   served products in this subcategory: 103
-- 306   Printers, Scanners & Fax   printers, scanners & fax   3   dim_contoso_product   I   served products in this subcategory: 101
-- 308   Computers Accessories   computers accessories   3   dim_contoso_product   I   served products in this subcategory: 201
-- 401   Digital Cameras   digital cameras   4   dim_contoso_product   I   served products in this subcategory: 100
-- 402   Digital SLR Cameras   digital slr cameras   4   dim_contoso_product   I   served products in this subcategory: 100
-- 405   Camcorders   camcorders   4   dim_contoso_product   I   served products in this subcategory: 103
-- 406   Cameras & Camcorders Accessories   cameras & camcorders accessories   4   dim_contoso_product   I   served products in this subcategory: 69
-- 501   Home & Office Phones   home & office phones   5   dim_contoso_product   I   served products in this subcategory: 92
-- 503   Touch Screen Phones   touch screen phones   5   dim_contoso_product   I   served products in this subcategory: 62
-- 504   Smart phones & PDAs   smart phones & pdas   5   dim_contoso_product   I   served products in this subcategory: 101
-- 505   Cell phones Accessories   cell phones accessories   5   dim_contoso_product   I   served products in this subcategory: 30
-- 602   Movie DVD   movie dvd   6   dim_contoso_product   I   served products in this subcategory: 90
-- 701   Boxed Games   boxed games   7   dim_contoso_product   I   served products in this subcategory: 46
-- 702   Download Games   download games   7   dim_contoso_product   I   served products in this subcategory: 120
-- 801   Washers & Dryers   washers & dryers   8   dim_contoso_product   I   served products in this subcategory: 70
-- 802   Refrigerators   refrigerators   8   dim_contoso_product   I   served products in this subcategory: 86
-- 803   Microwaves   microwaves   8   dim_contoso_product   I   served products in this subcategory: 102
-- 804   Water Heaters   water heaters   8   dim_contoso_product   I   served products in this subcategory: 31
-- 805   Coffee Machines   coffee machines   8   dim_contoso_product   I   served products in this subcategory: 74
-- 806   Lamps   lamps   8   dim_contoso_product   I   served products in this subcategory: 158
-- 807   Air Conditioners   air conditioners   8   dim_contoso_product   I   served products in this subcategory: 62
-- 808   Fans   fans   8   dim_contoso_product   I   served products in this subcategory: 78

-- ================================================================================================
-- L4 · cut contoso_weight_unit.lookup.csv from dim_contoso_product
-- ================================================================================================
SELECT "WeightUnit" AS "WeightUnit", "WeightUnit" AS label,
       lower(trim("WeightUnit")) AS search_key, 'dim_contoso_product' AS source_view, 'I' AS confidence,
       'served rows with this unit: ' || count(*) AS note
FROM contoso_served.dim_contoso_product
WHERE "WeightUnit" IS NOT NULL
GROUP BY "WeightUnit"
ORDER BY "WeightUnit";
-- ANSWER:
-- grams   grams   grams   dim_contoso_product   I   served rows with this unit: 10
-- ounces   ounces   ounces   dim_contoso_product   I   served rows with this unit: 418
-- pounds   pounds   pounds   dim_contoso_product   I   served rows with this unit: 1867

-- ================================================================================================
-- L4 · cut contoso_store_status.lookup.csv from dim_contoso_store
-- ================================================================================================
SELECT "Status" AS "Status", "Status" AS label, lower(trim("Status")) AS search_key,
       'dim_contoso_store' AS source_view, 'I' AS confidence,
       'served store versions with this status: ' || count(*) AS note
FROM contoso_served.dim_contoso_store
WHERE "Status" IS NOT NULL
GROUP BY "Status"
ORDER BY "Status";
-- ANSWER:
-- Closed   Closed   closed   dim_contoso_store   I   served store versions with this status: 8
-- Restructured   Restructured   restructured   dim_contoso_store   I   served store versions with this status: 7

-- ================================================================================================
-- L4 · cut contoso_gender.lookup.csv from dim_contoso_customer
-- ================================================================================================
SELECT "Gender" AS "Gender", "Gender" AS label, lower(trim("Gender")) AS search_key,
       'dim_contoso_customer' AS source_view, 'I' AS confidence,
       'served customers with this value: ' || count(*) AS note
FROM contoso_served.dim_contoso_customer
WHERE "Gender" IS NOT NULL
GROUP BY "Gender"
ORDER BY "Gender";
-- ANSWER:
-- female   female   female   dim_contoso_customer   I   served customers with this value: 51927
-- male   male   male   dim_contoso_customer   I   served customers with this value: 53063

-- ================================================================================================
-- L4 · cut contoso_currency.lookup.csv from v_contoso_order_line
-- ================================================================================================
-- Cut from the FACT, not from the FX relation: `CurrencyCode` is how the served fact spells
-- this code, and a register's code column must be spelled as the dataset it joins to spells it.
-- The FX relation spells the same codes `FromCurrency`/`ToCurrency`, and L7a measures the three
-- sets identical (5 of 5, 0 either way), so the choice of source loses no code.
SELECT "CurrencyCode" AS "CurrencyCode", '' AS label, '' AS search_key,
       'v_contoso_order_line' AS source_view, 'Q' AS confidence,
       'code measured on ' || count(*) || ' served order lines; no currency NAME exists anywhere in '
       'the delivery (L6d/L6d2), so the label is deliberately empty rather than recalled from '
       'outside the data' AS note
FROM contoso_served.v_contoso_order_line
GROUP BY "CurrencyCode"
ORDER BY "CurrencyCode";
-- ANSWER:
-- AUD         v_contoso_order_line   Q   code measured on 14078 served order lines; no currency NAME exists anywhere in the delivery (L6d/L6d2), so the label is deliberately empty rather than recalled from outside the data
-- CAD         v_contoso_order_line   Q   code measured on 24250 served order lines; no currency NAME exists anywhere in the delivery (L6d/L6d2), so the label is deliberately empty rather than recalled from outside the data
-- EUR         v_contoso_order_line   Q   code measured on 49203 served order lines; no currency NAME exists anywhere in the delivery (L6d/L6d2), so the label is deliberately empty rather than recalled from outside the data
-- GBP         v_contoso_order_line   Q   code measured on 22829 served order lines; no currency NAME exists anywhere in the delivery (L6d/L6d2), so the label is deliberately empty rather than recalled from outside the data
-- USD         v_contoso_order_line   Q   code measured on 113614 served order lines; no currency NAME exists anywhere in the delivery (L6d/L6d2), so the label is deliberately empty rather than recalled from outside the data

-- ================================================================================================
-- L4 · cut contoso_country.lookup.csv from dim_contoso_customer
-- ================================================================================================
-- 8 rows from the customer dimension (the only served relation carrying a continent) plus
-- the store dimension's sentinel, which is a country code in shape only.
SELECT "Country" AS "Country", "CountryFull" AS label, lower(trim("CountryFull")) AS search_key,
       "Continent" AS continent, 'dim_contoso_customer' AS source_view, 'I' AS confidence,
       'served customers in this country: ' || count(*) AS note
FROM contoso_served.dim_contoso_customer
GROUP BY "Country", "CountryFull", "Continent"
UNION ALL
SELECT "CountryCode", "CountryName", lower(trim("CountryName")), '',
       'dim_contoso_store', 'Q',
       'SENTINEL, not a country: the online store version carries CountryCode ''--'' and '
       'CountryName/State ''Online''. Kept so a store row always resolves; its continent is empty '
       'because the data states none. Whether ''--'' means ''no geography'' or ''global'' is an open '
       'ruling'
FROM contoso_served.dim_contoso_store
WHERE "CountryCode" NOT IN (SELECT "Country" FROM contoso_served.dim_contoso_customer)
GROUP BY "CountryCode", "CountryName"
ORDER BY 1;
-- ANSWER:
-- --   Online   online      dim_contoso_store   Q   SENTINEL, not a country: the online store version carries CountryCode '--' and CountryName/State 'Online'. Kept so a store row always resolves; its continent is empty because the data states none. Whether '--' means 'no geography' or 'global' is an open ruling
-- AU   Australia   australia   Australia   dim_contoso_customer   I   served customers in this country: 10108
-- CA   Canada   canada   North America   dim_contoso_customer   I   served customers in this country: 10111
-- DE   Germany   germany   Europe   dim_contoso_customer   I   served customers in this country: 9981
-- FR   France   france   Europe   dim_contoso_customer   I   served customers in this country: 4879
-- GB   United Kingdom   united kingdom   Europe   dim_contoso_customer   I   served customers in this country: 14781
-- IT   Italy   italy   Europe   dim_contoso_customer   I   served customers in this country: 5036
-- NL   Netherlands   netherlands   Europe   dim_contoso_customer   I   served customers in this country: 4911
-- US   United States   united states   North America   dim_contoso_customer   I   served customers in this country: 45183

-- ================================================================================================
-- L4 · cut contoso_geo_area.lookup.csv from dim_contoso_customer
-- ================================================================================================
SELECT "GeoAreaKey" AS "GeoAreaKey", "StateFull" AS label,
       lower(trim("StateFull")) AS search_key, "State" AS state_abbrev, "Country" AS country,
       'dim_contoso_customer' AS source_view, 'I' AS confidence,
       'served customers in this area: ' || count(*) AS note
FROM contoso_served.dim_contoso_customer
GROUP BY "GeoAreaKey", "StateFull", "State", "Country"
ORDER BY "GeoAreaKey";
-- ANSWER:
-- 1   Australian Capital Territory   australian capital territory   ACT   AU   dim_contoso_customer   I   served customers in this area: 100
-- 2   New South Wales   new south wales   NSW   AU   dim_contoso_customer   I   served customers in this area: 3155
-- 3   Northern Territory   northern territory   NT   AU   dim_contoso_customer   I   served customers in this area: 98
-- 4   Queensland   queensland   QLD   AU   dim_contoso_customer   I   served customers in this area: 2086
-- 5   South Australia   south australia   SA   AU   dim_contoso_customer   I   served customers in this area: 1153
-- 6   Tasmania   tasmania   TAS   AU   dim_contoso_customer   I   served customers in this area: 468
-- 7   Victoria   victoria   VIC   AU   dim_contoso_customer   I   served customers in this area: 1980
-- 8   Western Australia   western australia   WA   AU   dim_contoso_customer   I   served customers in this area: 1068
-- 9   Alberta   alberta   AB   CA   dim_contoso_customer   I   served customers in this area: 1485
-- 10   British Columbia   british columbia   BC   CA   dim_contoso_customer   I   served customers in this area: 1718
-- 11   Manitoba   manitoba   MB   CA   dim_contoso_customer   I   served customers in this area: 92
-- 12   New Brunswick   new brunswick   NB   CA   dim_contoso_customer   I   served customers in this area: 15
-- 13   Newfoundland and Labrador   newfoundland and labrador   NL   CA   dim_contoso_customer   I   served customers in this area: 19
-- 14   Nova Scotia   nova scotia   NS   CA   dim_contoso_customer   I   served customers in this area: 172
-- 15   Northwest Territories   northwest territories   NT   CA   dim_contoso_customer   I   served customers in this area: 47
-- 16   Nunavut   nunavut   NU   CA   dim_contoso_customer   I   served customers in this area: 43
-- 17   Ontario   ontario   ON   CA   dim_contoso_customer   I   served customers in this area: 4287
-- 18   Prince Edward Island   prince edward island   PE   CA   dim_contoso_customer   I   served customers in this area: 82
-- 19   Quebec   quebec   QC   CA   dim_contoso_customer   I   served customers in this area: 1643
-- 20   Saskatchewan   saskatchewan   SK   CA   dim_contoso_customer   I   served customers in this area: 476
-- 21   Yukon   yukon   YT   CA   dim_contoso_customer   I   served customers in this area: 32
-- 22   Brandenburg   brandenburg   BB   DE   dim_contoso_customer   I   served customers in this area: 259
-- 23   Berlin   berlin   BE   DE   dim_contoso_customer   I   served customers in this area: 183
-- 24   Baden-Württemberg   baden-württemberg   BW   DE   dim_contoso_customer   I   served customers in this area: 974
-- 25   Freistaat Bayern   freistaat bayern   BY   DE   dim_contoso_customer   I   served customers in this area: 2891
-- 26   Freie Hansestadt Bremen   freie hansestadt bremen   HB   DE   dim_contoso_customer   I   served customers in this area: 74
-- 27   Hessen   hessen   HE   DE   dim_contoso_customer   I   served customers in this area: 253
-- 28   Hamburg   hamburg   HH   DE   dim_contoso_customer   I   served customers in this area: 179
-- 29   Mecklenburg-Vorpommern   mecklenburg-vorpommern   MV   DE   dim_contoso_customer   I   served customers in this area: 234
-- 30   Niedersachsen   niedersachsen   NI   DE   dim_contoso_customer   I   served customers in this area: 701
-- 31   Nordrhein-Westfalen   nordrhein-westfalen   NW   DE   dim_contoso_customer   I   served customers in this area: 821
-- 32   Rheinland-Pfalz   rheinland-pfalz   RP   DE   dim_contoso_customer   I   served customers in this area: 1444
-- 33   Schleswig-Holstein   schleswig-holstein   SH   DE   dim_contoso_customer   I   served customers in this area: 631
-- 34   Saarland   saarland   SL   DE   dim_contoso_customer   I   served customers in this area: 57
-- 35   Freistaat Sachsen   freistaat sachsen   SN   DE   dim_contoso_customer   I   served customers in this area: 505
-- 36   Sachsen-Anhalt   sachsen-anhalt   ST   DE   dim_contoso_customer   I   served customers in this area: 339
-- 37   Freistaat Thüringen   freistaat thüringen   TH   DE   dim_contoso_customer   I   served customers in this area: 436
-- 38   Alsace   alsace   AL   FR   dim_contoso_customer   I   served customers in this area: 76
-- 39   Aquitaine   aquitaine   AQ   FR   dim_contoso_customer   I   served customers in this area: 236
-- 40   Auvergne   auvergne   AU   FR   dim_contoso_customer   I   served customers in this area: 60
--    ... 568 further row(s) not printed (608 in total)

-- ================================================================================================
-- L4 · cut dim_contoso_product.lookup.csv from dim_contoso_product
-- ================================================================================================
SELECT "ProductKey" AS "ProductKey", "ProductName" AS label,
       lower(trim("ProductName")) AS search_key, "ProductCode" AS product_code, "Brand" AS brand,
       "CategoryKey" AS category_key, "SubCategoryKey" AS subcategory_key,
       'dim_contoso_product' AS source_view, 'I' AS confidence, '' AS note
FROM contoso_served.dim_contoso_product
ORDER BY "ProductKey";
-- ANSWER:
-- 1   Contoso 512MB MP3 Player E51 Silver   contoso 512mb mp3 player e51 silver   0101001   Contoso   1   101   dim_contoso_product   I   
-- 2   Contoso 512MB MP3 Player E51 Blue   contoso 512mb mp3 player e51 blue   0101002   Contoso   1   101   dim_contoso_product   I   
-- 3   Contoso 1G MP3 Player E100 White   contoso 1g mp3 player e100 white   0101003   Contoso   1   101   dim_contoso_product   I   
-- 4   Contoso 2G MP3 Player E200 Silver   contoso 2g mp3 player e200 silver   0101004   Contoso   1   101   dim_contoso_product   I   
-- 5   Contoso 2G MP3 Player E200 Red   contoso 2g mp3 player e200 red   0101005   Contoso   1   101   dim_contoso_product   I   
-- 6   Contoso 2G MP3 Player E200 Black   contoso 2g mp3 player e200 black   0101006   Contoso   1   101   dim_contoso_product   I   
-- 7   Contoso 2G MP3 Player E200 Blue   contoso 2g mp3 player e200 blue   0101007   Contoso   1   101   dim_contoso_product   I   
-- 8   Contoso 4G MP3 Player E400 Silver   contoso 4g mp3 player e400 silver   0101008   Contoso   1   101   dim_contoso_product   I   
-- 9   Contoso 4G MP3 Player E400 Black   contoso 4g mp3 player e400 black   0101009   Contoso   1   101   dim_contoso_product   I   
-- 10   Contoso 4G MP3 Player E400 Green   contoso 4g mp3 player e400 green   0101010   Contoso   1   101   dim_contoso_product   I   
-- 11   Contoso 4G MP3 Player E400 Orange   contoso 4g mp3 player e400 orange   0101011   Contoso   1   101   dim_contoso_product   I   
-- 12   Contoso 4GB Flash MP3 Player E401 Blue   contoso 4gb flash mp3 player e401 blue   0101012   Contoso   1   101   dim_contoso_product   I   
-- 13   Contoso 4GB Flash MP3 Player E401 Black   contoso 4gb flash mp3 player e401 black   0101013   Contoso   1   101   dim_contoso_product   I   
-- 14   Contoso 4GB Flash MP3 Player E401 Silver   contoso 4gb flash mp3 player e401 silver   0101014   Contoso   1   101   dim_contoso_product   I   
-- 15   Contoso 4GB Flash MP3 Player E401 White   contoso 4gb flash mp3 player e401 white   0101015   Contoso   1   101   dim_contoso_product   I   
-- 16   Contoso 8GB Super-Slim MP3/Video Player M800 White   contoso 8gb super-slim mp3/video player m800 white   0101016   Contoso   1   101   dim_contoso_product   I   
-- 17   Contoso 8GB Super-Slim MP3/Video Player M800 Red   contoso 8gb super-slim mp3/video player m800 red   0101017   Contoso   1   101   dim_contoso_product   I   
-- 18   Contoso 8GB Super-Slim MP3/Video Player M800 Green   contoso 8gb super-slim mp3/video player m800 green   0101018   Contoso   1   101   dim_contoso_product   I   
-- 19   Contoso 8GB Super-Slim MP3/Video Player M800 Pink   contoso 8gb super-slim mp3/video player m800 pink   0101019   Contoso   1   101   dim_contoso_product   I   
-- 20   Contoso 8GB MP3 Player new model M820 Black   contoso 8gb mp3 player new model m820 black   0101020   Contoso   1   101   dim_contoso_product   I   
-- 21   Contoso 8GB MP3 Player new model M820 Blue   contoso 8gb mp3 player new model m820 blue   0101021   Contoso   1   101   dim_contoso_product   I   
-- 22   Contoso 8GB MP3 Player new model M820 Yellow   contoso 8gb mp3 player new model m820 yellow   0101022   Contoso   1   101   dim_contoso_product   I   
-- 23   Contoso 8GB MP3 Player new model M820 White   contoso 8gb mp3 player new model m820 white   0101023   Contoso   1   101   dim_contoso_product   I   
-- 24   Contoso 16GB Mp5 Player M1600 Blue   contoso 16gb mp5 player m1600 blue   0101024   Contoso   1   101   dim_contoso_product   I   
-- 25   Contoso 16GB Mp5 Player M1600 Black   contoso 16gb mp5 player m1600 black   0101025   Contoso   1   101   dim_contoso_product   I   
-- 26   Contoso 16GB Mp5 Player M1600 Green   contoso 16gb mp5 player m1600 green   0101026   Contoso   1   101   dim_contoso_product   I   
-- 27   Contoso 16GB Mp5 Player M1600 White   contoso 16gb mp5 player m1600 white   0101027   Contoso   1   101   dim_contoso_product   I   
-- 28   Contoso 16GB Mp5 Player M1600 Red   contoso 16gb mp5 player m1600 red   0101028   Contoso   1   101   dim_contoso_product   I   
-- 29   Contoso 32GB Video MP3 Player M3200 White   contoso 32gb video mp3 player m3200 white   0101029   Contoso   1   101   dim_contoso_product   I   
-- 30   Contoso 32GB Video MP3 Player M3200 Red   contoso 32gb video mp3 player m3200 red   0101030   Contoso   1   101   dim_contoso_product   I   
-- 31   Contoso 32GB Video MP3 Player M3200 Orange   contoso 32gb video mp3 player m3200 orange   0101031   Contoso   1   101   dim_contoso_product   I   
-- 32   Contoso 32GB Video MP3 Player M3200 Pink   contoso 32gb video mp3 player m3200 pink   0101032   Contoso   1   101   dim_contoso_product   I   
-- 33   Contoso 32GB Video MP3 Player M3200 Black   contoso 32gb video mp3 player m3200 black   0101033   Contoso   1   101   dim_contoso_product   I   
-- 34   Contoso 4GB Portable MP3 Player M450 Black   contoso 4gb portable mp3 player m450 black   0101034   Contoso   1   101   dim_contoso_product   I   
-- 35   Contoso 4GB Portable MP3 Player M450 White   contoso 4gb portable mp3 player m450 white   0101035   Contoso   1   101   dim_contoso_product   I   
-- 36   Contoso 4GB Portable MP3 Player M450 Yellow   contoso 4gb portable mp3 player m450 yellow   0101036   Contoso   1   101   dim_contoso_product   I   
-- 37   Contoso 8GB Clock & Radio MP3 Player X850 Silver   contoso 8gb clock & radio mp3 player x850 silver   0101037   Contoso   1   101   dim_contoso_product   I   
-- 38   Contoso 8GB Clock & Radio MP3 Player X850 Black   contoso 8gb clock & radio mp3 player x850 black   0101038   Contoso   1   101   dim_contoso_product   I   
-- 39   Contoso 8GB Clock & Radio MP3 Player X850 Green   contoso 8gb clock & radio mp3 player x850 green   0101039   Contoso   1   101   dim_contoso_product   I   
-- 40   Contoso 8GB Clock & Radio MP3 Player X850 Blue   contoso 8gb clock & radio mp3 player x850 blue   0101040   Contoso   1   101   dim_contoso_product   I   
--    ... 2477 further row(s) not printed (2517 in total)

-- ================================================================================================
-- L4 · cut dim_contoso_store.lookup.csv from dim_contoso_store
-- ================================================================================================
SELECT "StoreKey" AS "StoreKey", "Description" AS label,
       lower(trim("Description")) AS search_key, "StoreCode" AS store_code,
       "CountryCode" AS country, "State" AS state, "Status" AS status,
       'dim_contoso_store' AS source_view, 'I' AS confidence, '' AS note
FROM contoso_served.dim_contoso_store
ORDER BY "StoreKey";
-- ANSWER:
-- 10   Contoso Store Australian Capital Territory   contoso store australian capital territory   1   AU   Australian Capital Territory   NULL   dim_contoso_store   I   
-- 20   Contoso Store Northern Territory   contoso store northern territory   2   AU   Northern Territory   Closed   dim_contoso_store   I   
-- 30   Contoso Store South Australia   contoso store south australia   3   AU   South Australia   Restructured   dim_contoso_store   I   
-- 35   Contoso Store South Australia   contoso store south australia   3   AU   South Australia   NULL   dim_contoso_store   I   
-- 40   Contoso Store Tasmania   contoso store tasmania   4   AU   Tasmania   NULL   dim_contoso_store   I   
-- 50   Contoso Store Victoria   contoso store victoria   5   AU   Victoria   NULL   dim_contoso_store   I   
-- 60   Contoso Store Western Australia   contoso store western australia   6   AU   Western Australia   NULL   dim_contoso_store   I   
-- 70   Contoso Store New Brunswick   contoso store new brunswick   7   CA   New Brunswick   Restructured   dim_contoso_store   I   
-- 72   Contoso Store New Brunswick   contoso store new brunswick   7   CA   New Brunswick   Restructured   dim_contoso_store   I   
-- 74   Contoso Store New Brunswick   contoso store new brunswick   7   CA   New Brunswick   NULL   dim_contoso_store   I   
-- 80   Contoso Store Newfoundland and Labrador   contoso store newfoundland and labrador   8   CA   Newfoundland and Labrador   NULL   dim_contoso_store   I   
-- 90   Contoso Store Northwest Territories   contoso store northwest territories   9   CA   Northwest Territories   NULL   dim_contoso_store   I   
-- 100   Contoso Store Nunavut   contoso store nunavut   10   CA   Nunavut   NULL   dim_contoso_store   I   
-- 110   Contoso Store Yukon   contoso store yukon   11   CA   Yukon   Closed   dim_contoso_store   I   
-- 120   Contoso Store Basse-Normandie   contoso store basse-normandie   12   FR   Basse-Normandie   NULL   dim_contoso_store   I   
-- 130   Contoso Store Corse   contoso store corse   13   FR   Corse   NULL   dim_contoso_store   I   
-- 140   Contoso Store Franche-Comté   contoso store franche-comté   14   FR   Franche-Comté   NULL   dim_contoso_store   I   
-- 150   Contoso Store La Réunion   contoso store la réunion   15   FR   La Réunion   NULL   dim_contoso_store   I   
-- 160   Contoso Store Limousin   contoso store limousin   16   FR   Limousin   NULL   dim_contoso_store   I   
-- 170   Contoso Store Martinique   contoso store martinique   17   FR   Martinique   NULL   dim_contoso_store   I   
-- 180   Contoso Store Mayotte   contoso store mayotte   18   FR   Mayotte   NULL   dim_contoso_store   I   
-- 190   Contoso Store Berlin   contoso store berlin   19   DE   Berlin   NULL   dim_contoso_store   I   
-- 200   Contoso Store Brandenburg   contoso store brandenburg   20   DE   Brandenburg   Closed   dim_contoso_store   I   
-- 210   Contoso Store Freie Hansestadt Bremen   contoso store freie hansestadt bremen   21   DE   Freie Hansestadt Bremen   NULL   dim_contoso_store   I   
-- 220   Contoso Store Freistaat Thüringen   contoso store freistaat thüringen   22   DE   Freistaat Thüringen   NULL   dim_contoso_store   I   
-- 230   Contoso Store Hamburg   contoso store hamburg   23   DE   Hamburg   NULL   dim_contoso_store   I   
-- 240   Contoso Store Hessen   contoso store hessen   24   DE   Hessen   NULL   dim_contoso_store   I   
-- 250   Contoso Store Mecklenburg-Vorpommern   contoso store mecklenburg-vorpommern   25   DE   Mecklenburg-Vorpommern   Restructured   dim_contoso_store   I   
-- 255   Contoso Store Mecklenburg-Vorpommern   contoso store mecklenburg-vorpommern   25   DE   Mecklenburg-Vorpommern   NULL   dim_contoso_store   I   
-- 260   Contoso Store Saarland   contoso store saarland   26   DE   Saarland   NULL   dim_contoso_store   I   
-- 270   Contoso Store Sachsen-Anhalt   contoso store sachsen-anhalt   27   DE   Sachsen-Anhalt   NULL   dim_contoso_store   I   
-- 280   Contoso Store Caltanissetta   contoso store caltanissetta   28   IT   Caltanissetta   Closed   dim_contoso_store   I   
-- 290   Contoso Store Enna   contoso store enna   29   IT   Enna   NULL   dim_contoso_store   I   
-- 300   Contoso Store Pesaro   contoso store pesaro   30   IT   Pesaro   NULL   dim_contoso_store   I   
-- 310   Contoso Store Drenthe   contoso store drenthe   31   NL   Drenthe   NULL   dim_contoso_store   I   
-- 320   Contoso Store Flevoland   contoso store flevoland   32   NL   Flevoland   NULL   dim_contoso_store   I   
-- 330   Contoso Store Friesland   contoso store friesland   33   NL   Friesland   NULL   dim_contoso_store   I   
-- 340   Contoso Store Groningen   contoso store groningen   34   NL   Groningen   NULL   dim_contoso_store   I   
-- 350   Contoso Store Zeeland   contoso store zeeland   35   NL   Zeeland   Closed   dim_contoso_store   I   
-- 360   Contoso Store Armagh   contoso store armagh   36   GB   Armagh   NULL   dim_contoso_store   I   
--    ... 34 further row(s) not printed (74 in total)

-- ================================================================================================
-- L4 · cut contoso_calendar_month.lookup.csv from dim_contoso_calendar_day
-- ================================================================================================
SELECT "MonthNumber" AS "MonthNumber", "Month" AS label, lower(trim("Month")) AS search_key,
       "MonthShort" AS label_short, lower(trim("MonthShort")) AS search_key_short,
       "Quarter" AS quarter, 'dim_contoso_calendar_day' AS source_view, 'I' AS confidence,
       'calendar days in this month across the span: ' || count(*) AS note
FROM contoso_served.dim_contoso_calendar_day
GROUP BY "MonthNumber", "Month", "MonthShort", "Quarter"
ORDER BY "MonthNumber";
-- ANSWER:
-- 1   January   january   Jan   jan   Q1   dim_contoso_calendar_day   I   calendar days in this month across the span: 341
-- 2   February   february   Feb   feb   Q1   dim_contoso_calendar_day   I   calendar days in this month across the span: 311
-- 3   March   march   Mar   mar   Q1   dim_contoso_calendar_day   I   calendar days in this month across the span: 341
-- 4   April   april   Apr   apr   Q2   dim_contoso_calendar_day   I   calendar days in this month across the span: 330
-- 5   May   may   May   may   Q2   dim_contoso_calendar_day   I   calendar days in this month across the span: 341
-- 6   June   june   Jun   jun   Q2   dim_contoso_calendar_day   I   calendar days in this month across the span: 330
-- 7   July   july   Jul   jul   Q3   dim_contoso_calendar_day   I   calendar days in this month across the span: 341
-- 8   August   august   Aug   aug   Q3   dim_contoso_calendar_day   I   calendar days in this month across the span: 341
-- 9   September   september   Sep   sep   Q3   dim_contoso_calendar_day   I   calendar days in this month across the span: 330
-- 10   October   october   Oct   oct   Q4   dim_contoso_calendar_day   I   calendar days in this month across the span: 341
-- 11   November   november   Nov   nov   Q4   dim_contoso_calendar_day   I   calendar days in this month across the span: 330
-- 12   December   december   Dec   dec   Q4   dim_contoso_calendar_day   I   calendar days in this month across the span: 341

-- ================================================================================================
-- L4 · cut contoso_calendar_quarter.lookup.csv from dim_contoso_calendar_day
-- ================================================================================================
SELECT "Quarter" AS "Quarter", "Quarter" AS label, lower(trim("Quarter")) AS search_key,
       'dim_contoso_calendar_day' AS source_view, 'I' AS confidence,
       'member months: ' || list_aggregate(list_sort(list(DISTINCT "MonthNumber")), 'string_agg', '+')
       AS note
FROM contoso_served.dim_contoso_calendar_day
GROUP BY "Quarter"
ORDER BY "Quarter";
-- ANSWER:
-- Q1   Q1   q1   dim_contoso_calendar_day   I   member months: 1+2+3
-- Q2   Q2   q2   dim_contoso_calendar_day   I   member months: 4+5+6
-- Q3   Q3   q3   dim_contoso_calendar_day   I   member months: 7+8+9
-- Q4   Q4   q4   dim_contoso_calendar_day   I   member months: 10+11+12

-- ================================================================================================
-- L4 · cut contoso_calendar_weekday.lookup.csv from dim_contoso_calendar_day
-- ================================================================================================
SELECT "DayofWeekNumber" AS "DayofWeekNumber", "DayofWeek" AS label,
       lower(trim("DayofWeek")) AS search_key, "DayofWeekShort" AS label_short,
       lower(trim("DayofWeekShort")) AS search_key_short, 'dim_contoso_calendar_day' AS source_view, 'I' AS confidence,
       'calendar days: ' || count(*) || '; working days among them: '
       || count(*) FILTER (WHERE "WorkingDay" = 1) AS note
FROM contoso_served.dim_contoso_calendar_day
GROUP BY "DayofWeekNumber", "DayofWeek", "DayofWeekShort"
ORDER BY "DayofWeekNumber";
-- ANSWER:
-- 1   Sunday   sunday   Sun   sun   dim_contoso_calendar_day   I   calendar days: 574; working days among them: 0
-- 2   Monday   monday   Mon   mon   dim_contoso_calendar_day   I   calendar days: 574; working days among them: 505
-- 3   Tuesday   tuesday   Tue   tue   dim_contoso_calendar_day   I   calendar days: 574; working days among them: 569
-- 4   Wednesday   wednesday   Wed   wed   dim_contoso_calendar_day   I   calendar days: 574; working days among them: 567
-- 5   Thursday   thursday   Thu   thu   dim_contoso_calendar_day   I   calendar days: 574; working days among them: 558
-- 6   Friday   friday   Fri   fri   dim_contoso_calendar_day   I   calendar days: 574; working days among them: 561
-- 7   Saturday   saturday   Sat   sat   dim_contoso_calendar_day   I   calendar days: 574; working days among them: 0

-- ================================================================================================
-- L4 · cut contoso_working_day.lookup.csv from dim_contoso_calendar_day
-- ================================================================================================
SELECT "WorkingDay" AS "WorkingDay",
       CASE "WorkingDay" WHEN 1 THEN 'working day' ELSE 'non-working day' END AS label,
       CASE "WorkingDay" WHEN 1 THEN 'working day' ELSE 'non-working day' END AS search_key,
       'dim_contoso_calendar_day' AS source_view, 'I' AS confidence,
       'calendar days: ' || count(*) || '; of them on Sat/Sun: '
       || count(*) FILTER (WHERE "DayofWeekNumber" IN (1, 7)) AS note
FROM contoso_served.dim_contoso_calendar_day
GROUP BY "WorkingDay"
ORDER BY "WorkingDay" DESC;
-- ANSWER:
-- 1   working day   working day   dim_contoso_calendar_day   I   calendar days: 2760; of them on Sat/Sun: 0
-- 0   non-working day   non-working day   dim_contoso_calendar_day   I   calendar days: 1258; of them on Sat/Sun: 1148

-- ================================================================================================
-- L6a · the region abbreviation is NOT an identity: how many GeoAreaKeys share a `State` abbreviation with another area?
-- ================================================================================================
SELECT count(DISTINCT "State") AS abbreviations, count(DISTINCT "GeoAreaKey") AS areas, (SELECT count(*) FROM (SELECT "State" FROM contoso_served.dim_contoso_customer GROUP BY 1 HAVING count(DISTINCT "GeoAreaKey") > 1)) AS abbreviations_used_by_2plus_areas, (SELECT sum(n) FROM (SELECT count(DISTINCT "GeoAreaKey") n FROM contoso_served.dim_contoso_customer GROUP BY "State" HAVING count(DISTINCT "GeoAreaKey") > 1)) AS areas_sharing_an_abbreviation FROM contoso_served.dim_contoso_customer;
-- ANSWER:
-- 563   608   40   85

-- ================================================================================================
-- L6b · the store code is NOT an identity: StoreCodes carried by more than one StoreKey
-- ================================================================================================
SELECT count(*) AS store_versions, count(DISTINCT "StoreCode") AS store_codes, (SELECT count(*) FROM (SELECT "StoreCode" FROM contoso_served.dim_contoso_store GROUP BY 1 HAVING count(*) > 1)) AS codes_with_2plus_versions FROM contoso_served.dim_contoso_store;
-- ANSWER:
-- 74   67   6

-- ================================================================================================
-- L6c · label collisions ACROSS registers: is any continent value also a country label, and is any category name also a subcategory name?
-- ================================================================================================
SELECT (SELECT count(*) FROM (SELECT DISTINCT "Continent" c FROM contoso_served.dim_contoso_customer) x JOIN (SELECT DISTINCT "CountryFull" c FROM contoso_served.dim_contoso_customer) y ON x.c = y.c) AS continent_words_that_are_also_country_words, (SELECT list(c) FROM (SELECT DISTINCT "Continent" c FROM contoso_served.dim_contoso_customer INTERSECT SELECT DISTINCT "CountryFull" FROM contoso_served.dim_contoso_customer)) AS which, (SELECT count(*) FROM (SELECT DISTINCT "CategoryName" c FROM contoso_served.dim_contoso_product INTERSECT SELECT DISTINCT "SubCategoryName" FROM contoso_served.dim_contoso_product)) AS category_words_that_are_also_subcategory_words;
-- ANSWER:
-- 1   ['Australia']   0

-- ================================================================================================
-- L6d · is there ANY currency name in the delivery? (columns whose name suggests one, over all 70 served columns)
-- ================================================================================================
SELECT count(*) AS served_columns, count(*) FILTER (WHERE lower(column_name) LIKE '%currency%') AS currency_columns, list(column_name) FILTER (WHERE lower(column_name) LIKE '%currency%') AS which FROM information_schema.columns WHERE table_schema='contoso_served';
-- ANSWER:
-- 70   3   ['FromCurrency', 'ToCurrency', 'CurrencyCode']

-- ================================================================================================
-- L6d2 · are those three columns codes or names? (value length and cardinality — a name would be longer than 3 characters)
-- ================================================================================================
SELECT (SELECT max(length("CurrencyCode")) FROM contoso_served.v_contoso_order_line) AS fact_code_len, (SELECT max(length("FromCurrency")) FROM contoso_served.v_contoso_fx_rate_day) AS fx_from_len, (SELECT max(length("ToCurrency")) FROM contoso_served.v_contoso_fx_rate_day) AS fx_to_len, (SELECT count(DISTINCT "CurrencyCode") FROM contoso_served.v_contoso_order_line) AS fact_codes;
-- ANSWER:
-- 3   3   3   5

-- ================================================================================================
-- L6e · does a product NAME resolve to one key? (search_key uniqueness on the product register's cut)
-- ================================================================================================
SELECT count(*) AS products, count(DISTINCT lower(trim("ProductName"))) AS distinct_search_keys, count(DISTINCT "ProductCode") AS distinct_codes, count(DISTINCT "ProductName") AS distinct_names FROM contoso_served.dim_contoso_product;
-- ANSWER:
-- 2517   2517   2517   2517

-- ================================================================================================
-- L6f · does a store DESCRIPTION resolve to one version?
-- ================================================================================================
SELECT count(*) AS store_versions, count(DISTINCT "Description") AS distinct_descriptions, count(DISTINCT lower(trim("Description"))) AS distinct_search_keys FROM contoso_served.dim_contoso_store;
-- ANSWER:
-- 74   67   67

-- ================================================================================================
-- L6g · the month register carries two search keys: on how many months do they coincide?
-- ================================================================================================
SELECT count(*) AS months, count(*) FILTER (WHERE lower("Month") = lower("MonthShort")) AS coinciding, list(DISTINCT "Month") FILTER (WHERE lower("Month") = lower("MonthShort")) AS which FROM (SELECT DISTINCT "MonthNumber", "Month", "MonthShort" FROM contoso_served.dim_contoso_calendar_day);
-- ANSWER:
-- 12   1   ['May']

-- ================================================================================================
-- L7a · the fact's CurrencyCode set vs the FX relation's From/To sets
-- ================================================================================================
SELECT (SELECT count(DISTINCT "CurrencyCode") FROM contoso_served.v_contoso_order_line) AS fact_codes, (SELECT count(DISTINCT "FromCurrency") FROM contoso_served.v_contoso_fx_rate_day) AS fx_from, (SELECT count(DISTINCT "ToCurrency") FROM contoso_served.v_contoso_fx_rate_day) AS fx_to, (SELECT count(*) FROM (SELECT DISTINCT "CurrencyCode" FROM contoso_served.v_contoso_order_line EXCEPT SELECT DISTINCT "FromCurrency" FROM contoso_served.v_contoso_fx_rate_day)) AS fact_not_in_fx, (SELECT count(*) FROM (SELECT DISTINCT "FromCurrency" FROM contoso_served.v_contoso_fx_rate_day EXCEPT SELECT DISTINCT "CurrencyCode" FROM contoso_served.v_contoso_order_line)) AS fx_not_in_fact;
-- ANSWER:
-- 5   5   5   0   0

-- ================================================================================================
-- L7b · customer `Country` vs store `CountryCode`: the same code system?
-- ================================================================================================
SELECT (SELECT count(*) FROM (SELECT DISTINCT "Country" FROM contoso_served.dim_contoso_customer EXCEPT SELECT DISTINCT "CountryCode" FROM contoso_served.dim_contoso_store)) AS customer_only, (SELECT count(*) FROM (SELECT DISTINCT "CountryCode" FROM contoso_served.dim_contoso_store EXCEPT SELECT DISTINCT "Country" FROM contoso_served.dim_contoso_customer)) AS store_only, (SELECT list(DISTINCT "CountryCode") FROM contoso_served.dim_contoso_store WHERE "CountryCode" NOT IN (SELECT "Country" FROM contoso_served.dim_contoso_customer)) AS which_store_only;
-- ANSWER:
-- 0   1   ['--']

-- ================================================================================================
-- L7c · do the two relations AGREE on the country name for a shared code?
-- ================================================================================================
SELECT count(*) AS shared_codes, count(*) FILTER (WHERE name_c = name_s) AS agreeing, count(*) FILTER (WHERE name_c <> name_s) AS disagreeing FROM (SELECT DISTINCT "Country" code, "CountryFull" name_c FROM contoso_served.dim_contoso_customer) c JOIN (SELECT DISTINCT "CountryCode" code, "CountryName" name_s FROM contoso_served.dim_contoso_store) s USING (code);
-- ANSWER:
-- 8   8   0

-- ================================================================================================
-- L8a · every served order line's ProductKey / StoreKey / CustomerKey resolves in a register (lines that do NOT)
-- ================================================================================================
SELECT count(*) AS lines, count(*) FILTER (WHERE p."ProductKey" IS NULL) AS product_unresolved, count(*) FILTER (WHERE s."StoreKey" IS NULL) AS store_unresolved, count(*) FILTER (WHERE c."CustomerKey" IS NULL) AS customer_row_missing FROM contoso_served.v_contoso_order_line f LEFT JOIN contoso_served.dim_contoso_product p USING ("ProductKey") LEFT JOIN contoso_served.dim_contoso_store s USING ("StoreKey") LEFT JOIN contoso_served.dim_contoso_customer c USING ("CustomerKey");
-- ANSWER:
-- 223974   0   0   0

-- ================================================================================================
-- L8b · every served product's Brand / CategoryKey / SubCategoryKey / Color / WeightUnit value appears in its register (values that do NOT — a register cut from the same relation must resolve all of it)
-- ================================================================================================
SELECT count(*) AS products, count(*) FILTER (WHERE "Brand" IS NULL) AS brand_null, count(*) FILTER (WHERE "CategoryKey" IS NULL) AS category_null, count(*) FILTER (WHERE "SubCategoryKey" IS NULL) AS subcategory_null, count(*) FILTER (WHERE "Color" IS NULL) AS color_null, count(*) FILTER (WHERE "WeightUnit" IS NULL) AS weightunit_null FROM contoso_served.dim_contoso_product;
-- ANSWER:
-- 2517   0   0   0   0   222

-- ================================================================================================
-- L8c · every served customer's Country and GeoAreaKey resolves; every served store's CountryCode resolves
-- ================================================================================================
SELECT (SELECT count(*) FROM contoso_served.dim_contoso_customer WHERE "Country" IS NULL OR "GeoAreaKey" IS NULL) AS customers_unresolvable, (SELECT count(*) FROM contoso_served.dim_contoso_store WHERE "CountryCode" IS NULL) AS stores_unresolvable, (SELECT count(*) FROM contoso_served.v_contoso_order_line WHERE "CurrencyCode" IS NULL) AS lines_without_currency;
-- ANSWER:
-- 0   0   0

-- ================================================================================================
-- L8d · every calendar day's MonthNumber / Quarter / DayofWeekNumber / WorkingDay is a registered value
-- ================================================================================================
SELECT count(*) AS days, count(*) FILTER (WHERE "MonthNumber" NOT BETWEEN 1 AND 12) AS month_out_of_register, count(*) FILTER (WHERE "Quarter" NOT IN ('Q1','Q2','Q3','Q4')) AS quarter_out_of_register, count(*) FILTER (WHERE "DayofWeekNumber" NOT BETWEEN 1 AND 7) AS weekday_out_of_register, count(*) FILTER (WHERE "WorkingDay" NOT IN (0, 1)) AS workingday_out_of_register FROM contoso_served.dim_contoso_calendar_day;
-- ANSWER:
-- 4018   0   0   0   0

-- ================================================================================================
-- L9a · Color: the landing's spellings vs the served register's rows
-- ================================================================================================
SELECT (SELECT count(DISTINCT "Color") FROM main.product) AS raw_spellings, (SELECT count(DISTINCT "Color") FROM contoso_served.dim_contoso_product) AS served_values, (SELECT list(DISTINCT "Color") FROM main.product WHERE "Color" NOT IN (SELECT "Color" FROM contoso_served.dim_contoso_product)) AS spellings_a_raw_cut_would_have_added;
-- ANSWER:
-- 17   16   ['blue']

-- ================================================================================================
-- L9b · WeightUnit and Status: '' in the landing vs NULL on the served side
-- ================================================================================================
SELECT (SELECT count(*) FROM main.product WHERE "WeightUnit" = '') AS raw_weightunit_empty, (SELECT count(*) FROM contoso_served.dim_contoso_product WHERE "WeightUnit" IS NULL) AS served_null, (SELECT count(DISTINCT "WeightUnit") FROM main.product) AS raw_weightunit_values, (SELECT count(DISTINCT "WeightUnit") FROM contoso_served.dim_contoso_product) AS served_values, (SELECT count(*) FROM main.store WHERE "Status" = '') AS raw_status_empty, (SELECT count(DISTINCT "Status") FROM main.store) AS raw_status_values, (SELECT count(DISTINCT "Status") FROM contoso_served.dim_contoso_store) AS served_status_values;
-- ANSWER:
-- 222   222   4   3   58   3   2

-- ================================================================================================
-- L9c · the region labels: padded spellings in the landing vs the served register
-- ================================================================================================
SELECT (SELECT count(DISTINCT "State") FROM main.customer) AS raw_abbreviations, (SELECT count(DISTINCT "State") FROM contoso_served.dim_contoso_customer) AS served_abbreviations, (SELECT count(DISTINCT "StateFull") FROM main.customer) AS raw_names, (SELECT count(DISTINCT "StateFull") FROM contoso_served.dim_contoso_customer) AS served_names, (SELECT count(*) FROM main.customer WHERE "State" <> trim("State") OR "StateFull" <> trim("StateFull")) AS raw_padded_rows;
-- ANSWER:
-- 565   563   610   608   4

-- ================================================================================================
-- L10 · WorkingDay: which value means a working day? (measured, not assumed)
-- ================================================================================================
SELECT count(*) FILTER (WHERE "DayofWeekNumber" IN (1, 7)) AS weekend_days, count(*) FILTER (WHERE "DayofWeekNumber" IN (1, 7) AND "WorkingDay" = 1) AS weekend_days_flagged_1, count(*) FILTER (WHERE "DayofWeekNumber" BETWEEN 2 AND 6 AND "WorkingDay" = 0) AS weekdays_flagged_0_holidays, count(*) FILTER (WHERE "WorkingDay" = 1) AS days_flagged_1, count(*) AS days FROM contoso_served.dim_contoso_calendar_day;
-- ANSWER:
-- 1148   0   110   2760   4018

-- ================================================================================================
-- L11 · the year-quarter code: does YearQuarterNumber = Year*4 + quarter hold on every day?
-- ================================================================================================
SELECT count(*) AS days, count(*) FILTER (WHERE "YearQuarterNumber" = "Year" * 4 + CAST(substr("Quarter", 2, 1) AS INTEGER)) AS days_matching_the_arithmetic FROM contoso_served.dim_contoso_calendar_day;
-- ANSWER:
-- 4018   4018

-- ================================================================================================
-- L12a · City: the cardinality and the ambiguity that refuse it a register
-- ================================================================================================
SELECT count(DISTINCT "City") AS city_names, count(DISTINCT ("City", "State", "Country")) AS city_state_country_triples, (SELECT count(*) FROM (SELECT "City" FROM contoso_served.dim_contoso_customer GROUP BY 1 HAVING count(DISTINCT ("State", "Country")) > 1)) AS city_names_in_2plus_regions, count(DISTINCT "ZipCode") AS zip_codes FROM contoso_served.dim_contoso_customer;
-- ANSWER:
-- 34581   39459   2642   40639

-- ================================================================================================
-- L12b · Customer: is there anything to resolve a customer BY? (served columns that could carry a customer name)
-- ================================================================================================
SELECT count(*) AS served_customer_columns, count(*) FILTER (WHERE lower(column_name) LIKE '%name%') AS name_columns, list(column_name) AS which FROM information_schema.columns WHERE table_schema='contoso_served' AND table_name='dim_contoso_customer';
-- ANSWER:
-- 12   0   ['CustomerKey', 'GeoAreaKey', 'StartDT', 'EndDT', 'Continent', 'CountryFull', 'Country', 'StateFull', 'State', 'City', 'ZipCode', 'Gender']

-- ================================================================================================
-- L12c · the period labels a register would duplicate: YearMonth / YearQuarter / Year cardinality on the calendar, and the fact's own span
-- ================================================================================================
SELECT (SELECT count(DISTINCT "YearMonth") FROM contoso_served.dim_contoso_calendar_day) AS year_months, (SELECT count(DISTINCT "YearQuarter") FROM contoso_served.dim_contoso_calendar_day) AS year_quarters, (SELECT count(DISTINCT "Year") FROM contoso_served.dim_contoso_calendar_day) AS years, (SELECT max("Date") FROM contoso_served.dim_contoso_calendar_day) AS calendar_last_day, (SELECT max("OrderDate") FROM contoso_served.v_contoso_order_line) AS fact_last_order_date;
-- ANSWER:
-- 132   44   11   2026-12-31 00:00:00   2025-12-31 00:00:00

-- ================================================================================================
-- L13 · shape of every register written, checked offline over the files themselves: header[0] is the code column (check_no_fabricated_identifiers reads header[0] as the register's key); the code column is spelled as EVERY source relation of its rows spells it; the code column is unique (one row per code); how many rows' search keys are distinct (a fold that is not 1:1 over-selects, so it may never be used as an identity); no `#` preamble above the header (a preamble makes csv.DictReader take the comment as the header and the lookup and measure-registry gates then tick over zero parsed rows); and no register accidentally carries the measure-registry columns, which are P8's registry and not this step's
-- ================================================================================================
(offline check over data/lookups/*.lookup.csv and data/datasets/*.yaml);
-- ANSWER:
--    register | header[0] | rows | source_view(s) | code_col_on_all_sources | code_unique | distinct_search_keys | no_preamble | not_a_measure_registry
--    contoso_brand | Brand | 11 | dim_contoso_product | yes | yes | 11/11 | yes | yes
--    contoso_color | Color | 16 | dim_contoso_product | yes | yes | 16/16 | yes | yes
--    contoso_product_category | CategoryKey | 8 | dim_contoso_product | yes | yes | 8/8 | yes | yes
--    contoso_product_subcategory | SubCategoryKey | 32 | dim_contoso_product | yes | yes | 32/32 | yes | yes
--    contoso_weight_unit | WeightUnit | 3 | dim_contoso_product | yes | yes | 3/3 | yes | yes
--    contoso_store_status | Status | 2 | dim_contoso_store | yes | yes | 2/2 | yes | yes
--    contoso_gender | Gender | 2 | dim_contoso_customer | yes | yes | 2/2 | yes | yes
--    contoso_currency | CurrencyCode | 5 | v_contoso_order_line | yes | yes | none | yes | yes
--    contoso_country | Country | 9 | dim_contoso_customer,dim_contoso_store | NO on dim_contoso_store | yes | 9/9 | yes | yes
--    contoso_geo_area | GeoAreaKey | 608 | dim_contoso_customer | yes | yes | 608/608 | yes | yes
--    dim_contoso_product | ProductKey | 2517 | dim_contoso_product | yes | yes | 2517/2517 | yes | yes
--    dim_contoso_store | StoreKey | 74 | dim_contoso_store | yes | yes | 67/74 | yes | yes
--    contoso_calendar_month | MonthNumber | 12 | dim_contoso_calendar_day | yes | yes | 12/12 | yes | yes
--    contoso_calendar_quarter | Quarter | 4 | dim_contoso_calendar_day | yes | yes | 4/4 | yes | yes
--    contoso_calendar_weekday | DayofWeekNumber | 7 | dim_contoso_calendar_day | yes | yes | 7/7 | yes | yes
--    contoso_working_day | WorkingDay | 2 | dim_contoso_calendar_day | yes | yes | 2/2 | yes | yes

